// ********RoostGPT********
/*
Test generated by RoostGPT for test sampleRESTtest using AI Type Open AI and AI Model gpt-4-turbo

Test generated for /products_get for http method type GET in rest-assured framework

RoostTestHash=50b0ea8cc0


*/

// ********RoostGPT********
package com.bootexample4.RoostTest;

import io.restassured.RestAssured;
import io.restassured.path.json.JsonPath;
import io.restassured.response.Response;
import org.hamcrest.MatcherAssert;
import org.json.JSONObject;
import org.json.XML;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Map;

import static io.restassured.RestAssured.given;
import static org.hamcrest.Matchers.*;

public class ProductsGetTest {

    private List<Map<String, String>> envList;

    @BeforeEach
    public void setUp() {
        TestdataLoader dataLoader = new TestdataLoader();
        String[] envVarsList = {""};
        envList = dataLoader.load("src/test/java/com/bootexample4/RoostTest/productsGetTest.csv", envVarsList);
    }

    @Test
    public void productsGet_Test() {
        Integer testNumber = 1;
        for (Map<String, String> testData : envList) {
            RestAssured.baseURI = testData.getOrDefault("nnnn_BASE_URL", "http://52.66.106.18:8080/api");
            JSONObject requestBodyObject = testData.containsKey("RequestBody") ? new JSONObject(testData.get("RequestBody")) : new JSONObject();

            Response response = given()
                    .contentType(ContentType.JSON)
                    .body(requestBodyObject.toString())
                    .when()
                    .get("/products")
                    .then()
                    .extract().response();

            JsonPath responseJson = response.jsonPath();
            String contentType = response.contentType();

            System.out.printf("Test Case %d: productsGet_Test \n", testNumber++);
            System.out.println("Request: GET /products");
            System.out.println("Status Code: " + response.statusCode());

            validateStatusCode(response, testData);
            validateContentType(contentType, responseJson);
        }
    }

    private void validateStatusCode(Response response, Map<String, String> testData) {
        String statusCodeFromCSV = testData.get("statusCode");
        if (statusCodeFromCSV != null) {
            if (statusCodeFromCSV.contains("X")) {
                MatcherAssert.assertThat("Expected a status code of category " + statusCodeFromCSV,
                        String.valueOf(response.statusCode()).charAt(0), equalTo(statusCodeFromCSV.charAt(0)));
            } else {
                MatcherAssert.assertThat(String.valueOf(response.statusCode()), equalTo(statusCodeFromCSV));
            }
        } else {
            List<Integer> expectedStatusCodes = Arrays.asList(200);
            MatcherAssert.assertThat(response.statusCode(), is(in(expectedStatusCodes)));
        }
    }

    private void validateContentType(String contentType, JsonPath responseJson) {
        if (contentType.contains("application/xml") || contentType.contains("text/xml")) {
            String xmlResponse = response.asString();
            JSONObject jsonResponse = XML.toJSONObject(xmlResponse);
            JSONObject jsonData = jsonResponse.getJSONObject("xml");
            String jsonString = jsonData.toString();
            responseJson = new JsonPath(jsonString);
        } else if (!contentType.contains("application/json")) {
            System.out.println("Unsupported content type: " + contentType);
            return;
        }

        switch (response.statusCode()) {
            case 200:
                validateSuccessfulResponse(responseJson);
                break;
            case 400:
                validateErrorResponse(responseJson);
                break;
            case 404:
                validateNotFoundResponse(responseJson);
                break;
            case 422:
                validateUnprocessableEntityResponse(responseJson);
                break;
            default:
                System.out.println("Unhandled status code: " + response.statusCode());
        }
    }

    private void validateSuccessfulResponse(JsonPath responseJson) {
        System.out.println("Description: Successful operation");
        if (responseJson.get("id") != null) {
            MatcherAssert.assertThat(responseJson.get("id"), instanceOf(Integer.class));
        }
        if (responseJson.get("name") != null) {
            MatcherAssert.assertThat(responseJson.get("name"), instanceOf(String.class));
        }
        if (responseJson.get("description") != null) {
            MatcherAssert.assertThat(responseJson.get("description"), instanceOf(String.class));
        }
        if (responseJson.get("price") != null) {
            MatcherAssert.assertThat(responseJson.get("price"), instanceOf(Integer.class));
        }
    }

    private void validateErrorResponse(JsonPath responseJson) {
        String error = responseJson.get("error");
        MatcherAssert.assertThat("Error message should not be null", error, notNullValue());
        MatcherAssert.assertThat("Error message should be a string", error, instanceOf(String.class));
    }

    private void validateNotFoundResponse(JsonPath responseJson) {
        String message = responseJson.get("message");
        MatcherAssert.assertThat("Not Found message should be present", message, equalTo("Resource not found"));
    }

    private void validateUnprocessableEntityResponse(JsonPath responseJson) {
        String errorDetail = responseJson.get("errorDetail");
        MatcherAssert.assertThat("Error details should provide information", errorDetail, containsString("Invalid input"));
    }
}
