// ********RoostGPT********
/*
Test generated by RoostGPT for test sampleRESTtest using AI Type Open AI and AI Model gpt-4-turbo

Test generated for /products_post for http method type POST in rest-assured framework

RoostTestHash=c4679418bc


*/

// ********RoostGPT********
package com.bootexample4.RoostTest;

import io.restassured.RestAssured;
import io.restassured.path.json.JsonPath;
import io.restassured.http.ContentType;
import io.restassured.response.Response;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static io.restassured.RestAssured.given;
import java.util.HashMap;
import java.util.Map;
import java.util.ArrayList;
import java.util.List;
import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.Matchers.*;
import org.json.JSONObject;
import org.json.XML;
import org.json.JSONException;

public class ProductsPostTest {

    private List<Map<String, String>> envList = new ArrayList<>();

    @BeforeEach
    public void setUp() {
        TestdataLoader dataLoader = new TestdataLoader();
        String[] envVarsList = {""};
        envList = dataLoader.load("src/test/java/com/bootexample4/RoostTest/productsPostTest.csv", envVarsList);
    }

    @Test
    public void productsPostTest() {
        Integer testNumber = 1;
        for (Map<String, String> testData : envList) {
            String baseURI = testData.getOrDefault("nnnn_BASE_URL", "http://52.66.106.18:8080/api");
            RestAssured.baseURI = baseURI;

            JSONObject requestBodyObject = new JSONObject(testData.getOrDefault("RequestBody", "{}"));
            Response response = given()
                .contentType(ContentType.JSON)
                .body(requestBodyObject.toString())
                .when()
                .post("/products")
                .then()
                .extract().response();

            JsonPath responseJson = parseResponse(response);
            validateResponse(response, testData, responseJson);

            System.out.printf("Test Case %d: productsPost_Test\n", testNumber++);
            System.out.println("Request: POST /products");
            System.out.println("Status Code: " + response.statusCode());
        }
    }

    private JsonPath parseResponse(Response response) {
        String contentType = response.getContentType();
        if (contentType.contains("application/xml") || contentType.contains("text/xml")) {
            String xmlResponse = response.asString();
            JSONObject jsonResponse = XML.toJSONObject(xmlResponse);
            return new JsonPath(jsonResponse.toString());
        } else if (contentType.contains("application/json")) {
            return response.jsonPath();
        } else {
            System.out.println("Unsupported content type: " + contentType);
            return null;
        }
    }

    private void validateResponse(Response response, Map<String, String> testData, JsonPath responseJson) {
        int statusCode = response.statusCode();
        List<Integer> expectedStatusCodes = Arrays.asList(200, 400, 404, 422);

        if (testData.containsKey("statusCode")) {
            String statusCodeFromCSV = testData.get("statusCode");
            if (statusCodeFromCSV.contains("X")) {
                assertThat(String.valueOf(statusCode).charAt(0), equalTo(statusCodeFromCSV.charAt(0)));
            } else {
                assertThat(String.valueOf(statusCode), equalTo(statusCodeFromCSV));
            }
        } else {
            assertThat(statusCode, is(in(expectedStatusCodes)));
        }

        switch (statusCode) {
            case 200:
                validateSuccessResponse(responseJson);
                break;
            case 400:
                validateErrorResponse(responseJson);
                break;
            case 404:
                validateNotFoundResponse(responseJson);
                break;
            case 422:
                validateUnprocessableEntityResponse(responseJson);
                break;
            default:
                System.out.println("Unhandled status code: " + statusCode);
                break;
        }
    }

    private void validateSuccessResponse(JsonPath response) {
        if (response.get("id") != null) {
            assertThat(response.get("id"), instanceOf(Integer.class));
        }
        if (response.get("name") != null) {
            assertThat(response.get("name"), instanceOf(String.class));
        }
        if (response.get("description") != null) {
            assertThat(response.get("description"), instanceOf(String.class));
        }
        if (response.get("price") != null) {
            assertThat(response.get("price"), instanceOf(Integer.class));
        }
    }

    private void validateErrorResponse(JsonPath response) {
        assertThat(response.getString("error"), notNullValue());
        assertThat(response.getString("message"), notNullValue());
    }

    private void validateNotFoundResponse(JsonPath response) {
        assertThat(response.getString("error"), equalTo("Not Found"));
    }

    private void validateUnprocessableEntityResponse(JsonPath response) {
        assertThat(response.getString("error"), equalTo("Unprocessable Entity"));
        assertThat(response.getList("errors"), not(empty()));
    }
}
