// ********RoostGPT********
/*
Test generated by RoostGPT for test sampleRESTtest using AI Type Azure Open AI and AI Model roostgpt-4-32k

Test generated for /products/{productId}_delete for http method type DELETE in rest-assured framework

RoostTestHash=9de2306488


*/

// ********RoostGPT********
package com.bootexample4.RoostTest;

import io.restassured.RestAssured;
import io.restassured.path.json.JsonPath;
import io.restassured.http.ContentType;
import io.restassured.response.Response;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static io.restassured.RestAssured.given;
import org.hamcrest.MatcherAssert;
import static org.hamcrest.Matchers.*;
import org.json.JSONObject;
import org.json.XML;
import org.json.JSONException;
import java.util.*;

public class ProductsProductIdDeleteTest {

    private List<Map<String, String>> envList = new ArrayList<>();
  
    
    @BeforeEach
    public void setUp() {
        TestdataLoader dataLoader = new TestdataLoader();
        String[] envVarsList = {"productId"};
        envList = dataLoader.load("src\\test\\java\\com\\bootexample4\\RoostTest\\products_productIdDeleteTest.csv", envVarsList);
    }

    @Test  
    public void productsProductIdDeleteTest() throws JSONException {
        setUp();
        int testNumber = 1;
        for (Map<String, String> testData : envList) {
            String baseUri = Optional.ofNullable(testData.get("nnnn_BASE_URL")).orElse("http://52.66.106.18:8080/api");
            RestAssured.baseURI = baseUri;
          
            JSONObject requestBodyObject = new JSONObject();
            Optional.ofNullable(testData.get("RequestBody"))
                    .ifPresent(requestBody -> requestBodyObject = new JSONObject(requestBody));
                
            Response response = given()
                .pathParam("productId", Optional.ofNullable(testData.get("productId")).orElse(""))
                .when()
                .delete("/products/{productId}")  
                .then() 
                .extract().response(); 
             
            printTestDetails(testNumber++, response, testData);  
            validateResponse(response, testData);
        }  
    }

    private void printTestDetails(int testNumber, Response response, Map<String, String> testData) {
        System.out.printf("Test Case %d: productsProductIdDelete_Test \n", testNumber);
        System.out.println("Request: DELETE /products/{productId}");
        System.out.println("Status Code: " + response.statusCode());
    }

    private void validateResponse(Response response, Map<String, String> testData) {
        String stringifiedStatusCode = Integer.toString(response.statusCode());
        String contentType = response.getContentType();
        JsonPath jsonResponse;

        if (contentType.contains("application/xml") || contentType.contains("text/xml")) {
            String xmlResponse = response.asString();
            JSONObject jsonResponse = XML.toJSONObject(xmlResponse);
            String jsonString = jsonResponse.toString();
            jsonResponse = new JsonPath(jsonString);
        } else if(contentType.contains("application/json")){  
            jsonResponse = response.jsonPath();
        } else {
            System.out.println("Unsupported response content type: "+contentType);
        }

        if(stringifiedStatusCode.equals("200")){
            System.out.println("Description: Product deleted");
        }
        if(stringifiedStatusCode.equals("404")){
            System.out.println("Description: Not Found");
        }
    }
}
