// ********RoostGPT********
/*
Test generated by RoostGPT for test sampleRESTtest using AI Type Azure Open AI and AI Model roostgpt-4-32k

Test generated for /products/{productId}_get for http method type GET in rest-assured framework

RoostTestHash=aa3c7beccb

[
  {
    "ScenarioID": "1",
    "TestName": "testValidRequestReturns200",
    "Description": "Test a valid GET request with an existing productId",
    "Execution": {
      "Arrange": "Prepare a valid productId (e.g., 10)",
      "Act": "Send GET request to /products/10",
      "Assert": "Check for 200 status and that response body contains product details with id=10"
    },
    "Validation": "Ensure API successfully returns product details with valid input"
  },
  {
    "ScenarioID": "2",
    "TestName": "testProductNotFoundReturns404",
    "Description": "Test GET request with a non-existing productId",
    "Execution": {
      "Arrange": "Prepare a productId that doesn't exist (e.g., 99999)",
      "Act": "Send GET request to /products/99999",
      "Assert": "Check for 404 status and appropriate error message in response body"
    },
    "Validation": "Ensure API correctly handles non-existent product ID"
  },
  {
    "ScenarioID": "3",
    "TestName": "testMissingProductIdInPathReturns404",
    "Description": "Test GET request with a missing productId in the endpoint path",
    "Execution": {
      "Arrange": "Leave productId blank in the path",
      "Act": "Send GET request to /products/",
      "Assert": "Check for 404 status indicating invalid endpoint"
    },
    "Validation": "Ensure API rejects requests with missing required path parameter"
  },
  {
    "ScenarioID": "4",
    "TestName": "testInvalidProductIdTypeReturns400",
    "Description": "Test GET request with an invalid productId type (e.g., string instead of integer)",
    "Execution": {
      "Arrange": "Prepare an invalid productId like 'abc'",
      "Act": "Send GET request to /products/abc",
      "Assert": "Check for 400 status and appropriate error message"
    },
    "Validation": "Ensure API correctly handles invalid parameter type in path"
  },
  {
    "ScenarioID": "5",
    "TestName": "testProductIdAsNullReturns400",
    "Description": "Test GET request with productId explicitly set to null",
    "Execution": {
      "Arrange": "Prepare a null value for productId",
      "Act": "Send GET request to /products/null",
      "Assert": "Check for 400 status and appropriate error message"
    },
    "Validation": "Ensure API correctly identifies and rejects null parameter values"
  },
  {
    "ScenarioID": "6",
    "TestName": "testProductIdAsNegativeIntegerReturns404",
    "Description": "Test GET request with a negative productId (e.g., -1)",
    "Execution": {
      "Arrange": "Prepare a negative integer value for productId",
      "Act": "Send GET request to /products/-1",
      "Assert": "Check for 404 status indicating product not found"
    },
    "Validation": "Ensure API correctly handles invalid negative identifiers"
  },
  {
    "ScenarioID": "7",
    "TestName": "testValidRequestWithExtraHeaders",
    "Description": "Test GET request with valid productId and extra unnecessary headers",
    "Execution": {
      "Arrange": "Prepare a valid productId (e.g., 10) and extra headers",
      "Act": "Send GET request to /products/10 with additional headers",
      "Assert": "Check for 200 status and correct product details in response body"
    },
    "Validation": "Ensure API ignores unnecessary headers and processes the request correctly"
  },
  {
    "ScenarioID": "8",
    "TestName": "testRequestWithoutHeaders",
    "Description": "Test GET request without sending any headers",
    "Execution": {
      "Arrange": "Prepare a valid productId (e.g., 10) without headers",
      "Act": "Send GET request to /products/10",
      "Assert": "Check for 200 status and correct product details in response body"
    },
    "Validation": "Ensure API processes requests correctly, even if headers are absent"
  },
  {
    "ScenarioID": "9",
    "TestName": "testMalformedEndpointPathReturns404",
    "Description": "Test GET request with a malformed endpoint path",
    "Execution": {
      "Arrange": "Prepare a valid productId (e.g., 10) and malformed path like /productss/10",
      "Act": "Send GET request to /productss/10",
      "Assert": "Check for 404 status indicating endpoint not found"
    },
    "Validation": "Ensure API rejects requests to incorrect endpoint paths"
  },
  {
    "ScenarioID": "10",
    "TestName": "testCorrectProductIdReturnsExpectedProperties",
    "Description": "Test GET request with a valid productId to ensure response properties are correct",
    "Execution": {
      "Arrange": "Prepare a valid productId (e.g., 10)",
      "Act": "Send GET request to /products/10",
      "Assert": "Check that the response contains id, name, description, and price as defined in the schema"
    },
    "Validation": "Ensure API response matches the documented schema"
  }
]

*/

// ********RoostGPT********
package com.bootexample4.RoostTest;

import io.restassured.RestAssured;
import io.restassured.response.Response;
import org.hamcrest.MatcherAssert;
import org.json.JSONObject;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;

import static io.restassured.RestAssured.given;
import static org.hamcrest.Matchers.equalTo;

public class ProductsProductIdGetTest {

    private List<JSONObject> testCases;

    @BeforeEach
    public void setUp() {
        TestdataLoader dataloader = new TestdataLoader();
        testCases = dataloader.loadJson("src\\test\\java\\com\\bootexample4\\RoostTest\\products_productIdGetTest.JSON");
    }

    @Test
    public void ProductsProductIdGet_Test() {
        RestAssured.baseURI = "http://52.66.106.18:8080/api";
        int testNumber = 1;

        for (JSONObject testData : testCases) {
            String requestPath = resolvePath(testData.optJSONObject("path_params"), "/products/{productId}");
            Response response = executeRequest(testData, requestPath);

            validateResponse(testData, response, testNumber++);
        }
    }

    /**
     * Resolves path parameters in the endpoint path based on the test case data.
     */
    private String resolvePath(JSONObject pathParams, String basePath) {
        if (pathParams != null) {
            for (String key : pathParams.keySet()) {
                basePath = basePath.replace("{" + key + "}", pathParams.getString(key));
            }
        }
        return basePath;
    }

    /**
     * Sends the API request based on the data provided in the test case.
     */
    private Response executeRequest(JSONObject testData, String requestPath) {
        JSONObject requestHeader = testData.optJSONObject("request_header");
        JSONObject queryParams = testData.optJSONObject("query_params");
        JSONObject requestBody = testData.optJSONObject("request_body");

        String authToken = resolveAuthToken(requestHeader);

        // Configure request specification
        var req = given()
                .headers(extractHeaders(requestHeader, authToken))
                .queryParams(extractQueryParams(queryParams))
                .body(requestBody != null && requestBody.length() > 0 ? requestBody.toString() : null);

        // Perform GET request
        return req.when().get(requestPath).then().extract().response();
    }

    /**
     * Resolves Authorization token with priority: Environment > JSON configuration.
     */
    private String resolveAuthToken(JSONObject requestHeader) {
        String envAuthToken = System.getenv("AUTH_TOKEN");
        String defaultToken = "${AUTH_TOKEN}";
        return (envAuthToken != null && !envAuthToken.isEmpty()) ? envAuthToken : defaultToken;
    }

    /**
     * Extracts headers from the test data, resolving the Authorization header if needed.
     */
    private JSONObject extractHeaders(JSONObject requestHeader, String resolvedAuthToken) {
        JSONObject headers = new JSONObject();
        if (requestHeader != null) {
            Iterator<String> keys = requestHeader.keys();
            while (keys.hasNext()) {
                String key = keys.next();
                String value = requestHeader.getString(key);

                if ("Authorization".equalsIgnoreCase(key) && "${AUTH_TOKEN}".equalsIgnoreCase(value)) {
                    headers.put(key, "Bearer " + resolvedAuthToken);
                } else {
                    headers.put(key, value);
                }
            }
        }

        if (!headers.has("Authorization") && resolvedAuthToken != null) {
            headers.put("Authorization", "Bearer " + resolvedAuthToken);
        }

        return headers;
    }

    /**
     * Extracts query parameters from the test case data.
     */
    private JSONObject extractQueryParams(JSONObject queryParams) {
        return queryParams != null ? queryParams : new JSONObject();
    }

    /**
     * Validates the response based on the expected output defined in the test case.
     */
    private void validateResponse(JSONObject testData, Response response, int testNumber) {
        System.out.printf("Test Case %d: ProductsProductIdGet_Test\n", testNumber);
        System.out.println("Request: GET " + response.getDetailedCookies());
        System.out.println("Status Code: " + response.statusCode());

        if (testData.has("expected_status_code")) {
            int expectedCode = testData.getInt("expected_status_code");
            MatcherAssert.assertThat(
                    "Expected status code " + expectedCode + " but got " + response.statusCode(),
                    response.statusCode(),
                    equalTo(expectedCode)
            );
        }

        switch (response.statusCode()) {
            case 400 -> validateErrorResponse(response);
            case 404 -> validateNotFoundResponse(response);
            case 422 -> validateUnprocessableEntityResponse(response);
            case 200 -> validateSuccessResponse(response, testData);
            default -> System.out.println("No specific validation for status code: " + response.statusCode());
        }
    }

    /**
     * Validates a successful response (status code 200).
     */
    private void validateSuccessResponse(Response response, JSONObject testData) {
        if (testData.has("expected_response_body")) {
            JSONObject expectedBody = testData.getJSONObject("expected_response_body");
            for (String key : expectedBody.keySet()) {
                MatcherAssert.assertThat(
                        "Expected '" + key + "' to be " + expectedBody.get(key),
                        response.jsonPath().get(key),
                        equalTo(expectedBody.get(key))
                );
            }
        }
    }

    /**
     * Validates error response for status code 400.
     */
    private void validateErrorResponse(Response response) {
        MatcherAssert.assertThat("Expected error message for 400", response.jsonPath().getString("error.message"), equalTo("Invalid request"));
    }

    /**
     * Validates not found response for status code 404.
     */
    private void validateNotFoundResponse(Response response) {
        MatcherAssert.assertThat("Expected error message for 404", response.jsonPath().getString("error.message"), equalTo("Resource not found"));
    }

    /**
     * Validates unprocessable entity response for status code 422.
     */
    private void validateUnprocessableEntityResponse(Response response) {
        MatcherAssert.assertThat("Expected error message for 422", response.jsonPath().getString("error.message"), equalTo("Unprocessable entity"));
    }
}
