// ********RoostGPT********
/*
Test generated by RoostGPT for test sampleRESTtest using AI Type Azure Open AI and AI Model roostgpt-4-32k

Test generated for /products_post for http method type POST in rest-assured framework

RoostTestHash=3f231531c5


*/

// ********RoostGPT********
package com.bootexample4.RoostTest;

import io.restassured.RestAssured;
import io.restassured.path.json.JsonPath;
import io.restassured.http.ContentType;
import io.restassured.response.Response;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static io.restassured.RestAssured.given;
import java.util.*;
import static org.hamcrest.Matchers.*;
import static org.hamcrest.MatcherAssert.assertThat;
import org.json.*;

public class ProductsPostTest {
    
    private List<Map<String, String>> envList;

    @BeforeEach
    public void setUp() {
        TestdataLoader dataloader = new TestdataLoader();
        String[] envVarsList = {""};
        envList = dataloader.load("src/test/java/com/bootexample4/RoostTest/productsPostTest.csv", envVarsList);
    }

    @Test  
    public void productsPost_Test() throws JSONException {
        int testNumber = 1;
        for (Map<String, String> testData : envList) {
            RestAssured.baseURI = Optional.ofNullable(testData.get("nnnn_BASE_URL")).filter(s -> !s.isEmpty()).orElse("http://52.66.106.18:8080/api");  
          
            JSONObject requestBodyObject = Optional.ofNullable(testData.get("RequestBody")).map(JSONObject::new).orElse(new JSONObject());
                      
            Response response = given()
                .contentType(ContentType.JSON)
                .body(requestBodyObject.toString())
                .post("/products")
                .then()
                .extract().response(); 
              
            String contentType = response.getContentType();

            System.out.printf("Test Case %d: productsPost_Test \n", testNumber++);
            System.out.println("Request: POST /products");
            System.out.println("Status Code: " + response.statusCode());
          
            String statusCodeFromCSV = testData.get("statusCode");
            validateResponseStatusCode(response, statusCodeFromCSV);
            
            JsonPath jsonPath;
            if (contentType.contains("application/xml") || contentType.contains("text/xml")) {
                JSONObject jsonResponse = XML.toJSONObject(response.asString());
                JSONObject jsonData = jsonResponse.getJSONObject("xml");
                String jsonString = jsonData.toString();
                jsonPath = new JsonPath(jsonString);
            } else if(contentType.contains("application/json")){
                jsonPath = response.jsonPath();
            } else {
                System.out.println("Unsupported content type: "+contentType);
                continue;
            }         
            validateResponseBody(jsonPath, response.statusCode());
        }
    }

    private void validateResponseStatusCode(Response response, String statusCodeFromCSV) {
        int actualStatusCode = response.statusCode();
        if (statusCodeFromCSV != null) {
            if (statusCodeFromCSV.contains("X")) {
                assertThat("Expected a status code of category " + statusCodeFromCSV + ", but got " + actualStatusCode + " instead", actualStatusCode / 100, equalTo(Integer.parseInt(String.valueOf(statusCodeFromCSV.charAt(0)))));
            } else {
                assertThat(actualStatusCode, equalTo(Integer.parseInt(statusCodeFromCSV)));
            }
        } else {
            assertThat(actualStatusCode, anyOf(equalTo(200), equalTo(405)));
        }
    }

    private void validateResponseBody(JsonPath jsonPath, int actualStatusCode) {
        if (actualStatusCode == 200) {
            System.out.println("Description: Successful operation");
            assertThat(jsonPath.get("id"), instanceOf(Integer.class));
            assertThat(jsonPath.get("name"), instanceOf(String.class));
            assertThat(jsonPath.get("description"), instanceOf(String.class));
            assertThat(jsonPath.get("price"), instanceOf(Float.class));
        } else if (actualStatusCode == 405) {
            System.out.println("Description: Invalid input");
        }
    }  
}
