// ********RoostGPT********
/*
Test generated by RoostGPT for test sampleRESTtest using AI Type Azure Open AI and AI Model roostgpt-4-32k

Test generated for /products/{productId}_put for http method type PUT in rest-assured framework

RoostTestHash=98f93fa50b


*/

// ********RoostGPT********
package com.bootexample4.RoostTest;

import io.restassured.RestAssured;
import io.restassured.path.json.JsonPath;
import io.restassured.http.ContentType;
import io.restassured.response.Response;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static io.restassured.RestAssured.given;
import static org.hamcrest.Matchers.*;
import static org.hamcrest.MatcherAssert.assertThat;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.json.XML;
import org.json.JSONObject;
import org.json.JSONException;

public class productsProductIdPutTest {

    private List<Map<String, String>> envList = new ArrayList<>();

    @BeforeEach
    public void setUp() {
        TestdataLoader dataloader = new TestdataLoader();
        String[] envVarsList = {"productId"};
        envList = dataloader.load("src\\test\\java\\com\\bootexample4\\RoostTest\\products_productIdPutTest.csv", envVarsList);
    }

    @Test
    public void productsProductIdPut_Test() throws JSONException {
        
        int testNumber = 1;
        
        for (Map<String, String> testData : envList) {

            String baseURI = testData.getOrDefault("nnnn_BASE_URL", "http://52.66.106.18:8080/api");
			
            JSONObject requestBodyObject = new JSONObject();
            if(testData.get("RequestBody") != null){
                requestBodyObject = new JSONObject(testData.get("RequestBody"));
            }

            Response responseObj = given()
                .baseUri(baseURI)
                .pathParam("productId", testData.getOrDefault("productId", ""))
                .contentType(ContentType.JSON)
                .body(requestBodyObject.toString())
                .when()
                .put("/products/{productId}")  
                .then()
                .extract().response(); 

            JsonPath response;

            String contentType = responseObj.getContentType();

            System.out.printf("Test Case %d: productsProductIdPut_Test \n", testNumber++);
            System.out.println("Request: PUT /products/{productId}");
            System.out.println("Status Code: " + responseObj.statusCode());

            validateResponse(testData, responseObj);

            switch(contentType) {
                case "application/xml":
                case "text/xml":
                    String xmlResponse = responseObj.asString();
					JSONObject jsonResponse = XML.toJSONObject(xmlResponse);
                    response = new JsonPath(jsonResponse.toString());
                    break;
                
                case "application/json":
                    response = responseObj.jsonPath();
                    break;
                
                default:
                    System.out.println("Unsupported content type: " + contentType);
                    continue;
            }

            validateContent(response, responseObj.statusCode());
        }  
    }

    private void validateResponse(Map<String, String> testData, Response responseObj) {
        String statusCodeFromCSV = testData.get("statusCode");
        if (statusCodeFromCSV != null) {
            if (statusCodeFromCSV.contains("X")) {
                assertThat(
                    responseObj.statusCode(),
                    equalTo(Integer.parseInt(statusCodeFromCSV))
                );
            } else {
                assertThat(
                    responseObj.statusCode(),
                    equalTo(Integer.parseInt(statusCodeFromCSV.charAt(0) + "00"))
                );
            }
        }  else {
            List<Integer> expectedStatusCodes = List.of(200, 404);
            assertThat(responseObj.statusCode(), is(in(expectedStatusCodes)));
        }
    }

    private void validateContent(JsonPath response, int statusCode) {
        if(statusCode == 200){
            System.out.println("Description: Updated Product");
            assertThat(response.get("id"), instanceOf(Integer.class));
            assertThat(response.get("name"), instanceOf(String.class));
            assertThat(response.get("description"), instanceOf(String.class));
            assertThat(response.get("price"), instanceOf(Integer.class));
        }

        if(statusCode == 404){
            System.out.println("Description: Not Found");
            // Add specific validation for 404 scenario.           
        }
        
        // Similar validations for other status codes.
    }
}

