// ********RoostGPT********
/*
Test generated by RoostGPT for test sampleRESTtest using AI Type Azure Open AI and AI Model roostgpt-4-32k

Test generated for /products/{productId}_delete for http method type DELETE in rest-assured framework

RoostTestHash=9de2306488


*/

// ********RoostGPT********
package com.bootexample4.RoostTest;

import io.restassured.RestAssured;
import io.restassured.path.json.JsonPath;
import io.restassured.http.ContentType;
import io.restassured.response.Response;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static io.restassured.RestAssured.given;
import org.hamcrest.MatcherAssert;
import static org.hamcrest.Matchers.*;

import java.util.*;

public class ProductsProductIdDeleteTest {

    private List<Map<String, String>> envList;

    public static final String DEFAULT_URI = "http://52.66.106.18:8080/api";

    @BeforeEach
    public void setUp() {
      TestdataLoader dataloader = new TestdataLoader();
      envList = dataloader.load("src/test/java/com/bootexample4/RoostTest/products_productIdDeleteTest.csv", "productId");
    }

    @Test  
    public void shouldDeleteProduct() throws JSONException {
        int testNumber = 1;
        for (Map<String, String> testData : envList) {
          String baseUrl = Optional.ofNullable(testData.get("nnnn_BASE_URL")).filter(val -> !val.isEmpty()).orElse(DEFAULT_URI);
          RestAssured.baseURI = baseUrl; 
          
          String productId = Optional.ofNullable(testData.get("productId")).orElse("");
          Response response = given()
            .pathParam("productId", productId)
            .when()
            .delete("/products/{productId}")
            .then()
            .extract()
            .response();

          validateResponse(testData, response, testNumber++);
        }
    }

    private void validateResponse(Map<String, String> testData, Response response, int testNumber) {
        System.out.printf("Test Case %d: productsProductIdDelete_Test \n", testNumber);
        System.out.println("Request: DELETE /products/{productId}");
        System.out.println("Status Code: " + response.statusCode());

        String expectedStatusCode = testData.get("statusCode");
        if (expectedStatusCode != null) {
            validateStatusCode(response, expectedStatusCode);
        } else {
            MatcherAssert.assertThat(response.statusCode(), is(in(Arrays.asList(200,404))));
        }

		JsonPath jsonResponse = getJsonPath(response);

        switch (response.statusCode()) {
            case 200:
                System.out.println("Description: Product deleted");
                break;
            case 404:
                System.out.println("Description: Not Found");
                break;
            default:
                throw new IllegalArgumentException("Unexpected status code: " + response.statusCode());
        }
    }

	private JsonPath getJsonPath(Response response) {
		String contentType = response.contentType();
		if (contentType.contains("application/xml") || contentType.contains("text/xml")) {
            return getJsonPathFromXml(response);
        } else if(contentType.contains("application/json")){
            return response.jsonPath();
        } else {
            throw new IllegalArgumentException("Unsupported content type: " + contentType);
        }
	}

    private JsonPath getJsonPathFromXml(Response response) {
        JSONObject jsonResponse = XML.toJSONObject(response.asString());
        JSONObject jsonData = jsonResponse.getJSONObject("xml");
        return new JsonPath(jsonData.toString());
    }

    private void validateStatusCode(Response response, String statusCodeFromCSV) {
        if (statusCodeFromCSV.contains("X")) {
            MatcherAssert.assertThat(
                "Expected a status code of category " + statusCodeFromCSV + ", but got "
                + Integer.toString(response.statusCode()) + " instead",
                Integer.toString(response.statusCode()).charAt(0), equalTo(statusCodeFromCSV.charAt(0)));
         } else {
            MatcherAssert.assertThat(
                Integer.toString(response.statusCode()), equalTo(statusCodeFromCSV));
         }
    }
}
