// ********RoostGPT********
/*
Test generated by RoostGPT for test sampleRESTtest using AI Type Azure Open AI and AI Model roostgpt-4-32k

Test generated for /products/{productId}_put for http method type PUT in rest-assured framework

RoostTestHash=98f93fa50b

[
  {
    "ScenarioID": "1",
    "TestName": "testUpdateProductSuccessful",
    "Description": "Test a valid request to update a product",
    "Execution": {
      "Arrange": "Prepare path param: productId=101 and form data {name: 'apple', description: 'description of the product', price: 20}",
      "Act": "Send PUT request to /products/101 with valid path and body parameters",
      "Assert": "Check for 200 status code and response body includes id=101, name='apple', description='description of the product', price=20"
    },
    "Validation": "Ensures API successfully updates the product details when valid data is provided"
  },
  {
    "ScenarioID": "2",
    "TestName": "testMissingPathParam",
    "Description": "Test response when required path parameter is missing",
    "Execution": {
      "Arrange": "Do not include path parameter productId",
      "Act": "Send PUT request to /products/",
      "Assert": "Check for 404 status code or appropriate error message in the response"
    },
    "Validation": "Ensures API properly handles requests with missing required path parameters"
  },
  {
    "ScenarioID": "3",
    "TestName": "testInvalidPathParamType",
    "Description": "Test response when path parameter is of invalid type",
    "Execution": {
      "Arrange": "Provide path param productId='abc' (string instead of integer)",
      "Act": "Send PUT request to /products/abc",
      "Assert": "Check for 400 status code and validate error message indicating invalid type for productId"
    },
    "Validation": "Ensures API validates the path parameter type correctly"
  },
  {
    "ScenarioID": "4",
    "TestName": "testUpdateProductWithoutRequiredProperty",
    "Description": "Test response when required form property 'name' is missing",
    "Execution": {
      "Arrange": "Prepare path param: productId=102 and form data {description: 'description', price: 20}",
      "Act": "Send PUT request to /products/102 with 'name' missing in body",
      "Assert": "Check for 400 status code and validate response error mentioning missing 'name' property"
    },
    "Validation": "Ensures API enforces required properties in the request body"
  },
  {
    "ScenarioID": "5",
    "TestName": "testUpdateProductNullRequiredProperty",
    "Description": "Test response when required form property 'name' is null",
    "Execution": {
      "Arrange": "Prepare path param: productId=103 and form data {name: null, description: 'description', price: 20}",
      "Act": "Send PUT request to /products/103 with 'name' set to null",
      "Assert": "Check for 400 status code and validate response error mentioning invalid value for 'name'"
    },
    "Validation": "Ensures API validates required properties properly, even for null values"
  },
  {
    "ScenarioID": "6",
    "TestName": "testUpdateProductInvalidFormDataType",
    "Description": "Test response when form data contains properties of invalid type",
    "Execution": {
      "Arrange": "Prepare path param: productId=104 and form data {name: 'banana', description: 12345, price: 'twenty'}",
      "Act": "Send PUT request to /products/104 with invalid data types in the form body",
      "Assert": "Check for 400 status code and validate response error mentioning invalid data types"
    },
    "Validation": "Ensures API validates form body property types correctly"
  },
  {
    "ScenarioID": "7",
    "TestName": "testUpdateNonExistentProduct",
    "Description": "Test response when attempting to update a non-existent product",
    "Execution": {
      "Arrange": "Prepare path param: productId=99999 with valid form data {name: 'grape', description: 'description', price: 30}",
      "Act": "Send PUT request to /products/99999",
      "Assert": "Check for 404 status code and validate response error mentioning product not found"
    },
    "Validation": "Ensures API responds appropriately when attempting to update a product that does not exist"
  },
  {
    "ScenarioID": "8",
    "TestName": "testMalformedRequestBody",
    "Description": "Test response when request body is malformed",
    "Execution": {
      "Arrange": "Prepare path param: productId=105 and malformed form data {name: 'orange', price: 'abc'}",
      "Act": "Send PUT request to /products/105 with malformed or incorrectly structured form data",
      "Assert": "Check for 400 status code and validate response error mentioning malformed body"
    },
    "Validation": "Ensures API identifies and handles malformed request body structures"
  },
  {
    "ScenarioID": "9",
    "TestName": "testUpdateProductNegativePrice",
    "Description": "Test response when form data has a negative price value",
    "Execution": {
      "Arrange": "Prepare path param: productId=106 and form data {name: 'pear', description: 'desc', price: -10}",
      "Act": "Send PUT request to /products/106 with the negative price value",
      "Assert": "Check for 400 status code and validate response error mentioning invalid price value"
    },
    "Validation": "Ensures API validates numeric constraints such as non-negative values correctly"
  },
  {
    "ScenarioID": "10",
    "TestName": "testUpdateProductWithExtraFormProperties",
    "Description": "Test response when form data includes unexpected additional properties",
    "Execution": {
      "Arrange": "Prepare path param: productId=107 and form data {name: 'peach', description: 'desc', price: 15, extra: 'unexpected'}",
      "Act": "Send PUT request to /products/107 with additional unexpected properties",
      "Assert": "Check for 200 status code if extra properties are ignored or 400 if rejected; validate response behavior"
    },
    "Validation": "Ensures API handles unexpected properties in the form data as per specification"
  }
]

*/

// ********RoostGPT********
package com.bootexample4.RoostTest;

import org.json.JSONObject;
import io.restassured.RestAssured;
import io.restassured.response.Response;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static io.restassured.RestAssured.given;
import static org.hamcrest.Matchers.*;
import org.hamcrest.MatcherAssert;
import java.util.*;

public class ProductsProductIdPutTest {

    private List<JSONObject> testCases;
    private static final String BASE_URI = "http://52.66.106.18:8080/api";
    private static final String AUTH_TOKEN_PLACEHOLDER = "${AUTH_TOKEN}";

    // Load test data before each test execution
    @BeforeEach
    public void setUp() {
        TestdataLoader dataloader = new TestdataLoader();
        testCases = dataloader.loadJson("src\\test\\java\\com\\bootexample4\\RoostTest\\products_productIdPutTest.JSON");
        RestAssured.baseURI = BASE_URI;
    }

    @Test
    public void runUpdateProductTests() {
        int testNumber = 1;

        for (JSONObject testData : testCases) {
            System.out.printf("Executing Test Case %d: %s%n", testNumber++, testData.optString("TestName"));

            String requestPath = constructPath(testData.optJSONObject("path_params"), "/products/{productId}");
            Response response = sendPutRequest(
                    requestPath,
                    resolveHeaders(testData.optJSONObject("request_header")),
                    testData.optJSONObject("query_params"),
                    testData.optJSONObject("request_body")
            );

            System.out.printf("Request Path: %s%n", requestPath);
            System.out.printf("Response Status Code: %d%n", response.statusCode());
            response.prettyPrint();

            validateResponse(testData, response);
        }
    }

    // Helper function to construct the path dynamically based on path params
    private String constructPath(JSONObject pathParams, String pathTemplate) {
        if (pathParams != null) {
            for (String key : pathParams.keySet()) {
                pathTemplate = pathTemplate.replace("{" + key + "}", pathParams.getString(key));
            }
        }
        return pathTemplate;
    }

    // Helper function to resolve headers (including dynamic Authorization token)
    private Map<String, String> resolveHeaders(JSONObject requestHeader) {
        Map<String, String> headers = new HashMap<>();
        String resolvedAuthToken = System.getenv("AUTH_TOKEN");

        if (requestHeader != null) {
            for (String key : requestHeader.keySet()) {
                String value = requestHeader.getString(key);

                if (key.equalsIgnoreCase("Authorization") && value.equals(AUTH_TOKEN_PLACEHOLDER)) {
                    headers.put(key, "Bearer " + resolvedAuthToken);
                } else {
                    headers.put(key, value);
                }
            }
        }

        // Add resolved Authorization token if no Authorization header exists
        if (!headers.containsKey("Authorization") && resolvedAuthToken != null) {
            headers.put("Authorization", "Bearer " + resolvedAuthToken);
        }

        return headers;
    }

    // Helper function to send PUT requests with dynamically configured parameters
    private Response sendPutRequest(String requestPath, Map<String, String> headers, JSONObject queryParams, JSONObject requestBody) {
        var req = given();

        // Add headers
        if (headers != null) {
            req.headers(headers);
        }

        // Add query parameters
        if (queryParams != null) {
            for (String key : queryParams.keySet()) {
                req.queryParam(key, queryParams.get(key));
            }
        }

        // Add request body
        if (requestBody != null && requestBody.length() > 0) {
            req.body(requestBody.toString());
        }

        return req.when().put(requestPath).then().extract().response();
    }

    // Helper function to validate the response based on expected data
    private void validateResponse(JSONObject testData, Response response) {
        int statusCode = response.statusCode();

        // Validate expected status code
        if (testData.has("expected_status_code")) {
            int expectedCode = testData.getInt("expected_status_code");
            MatcherAssert.assertThat("Expected status code mismatch.", statusCode, equalTo(expectedCode));
        }

        // Status-specific validation functions
        switch (statusCode) {
            case 400:
                validateErrorResponse(response);
                break;
            case 404:
                validateNotFoundResponse(response);
                break;
            case 422:
                validateUnprocessableEntityResponse(response);
                break;
            case 200:
                validateSuccessfulUpdateResponse(response, testData.optJSONObject("expected_response"));
                break;
            default:
                System.err.printf("Unhandled status code: %d%n", statusCode);
        }
    }

    // Validation for successful product update (status code 200)
    private void validateSuccessfulUpdateResponse(Response response, JSONObject expectedResponse) {
        if (expectedResponse != null) {
            for (String key : expectedResponse.keySet()) {
                response.then().body(key, equalTo(expectedResponse.get(key)));
            }
        } else {
            System.err.println("Missing expected response configuration for status code 200.");
        }
    }

    // Validation for error responses (status code 400)
    private void validateErrorResponse(Response response) {
        response.then().body("error", notNullValue());
        response.then().body("message", containsStringIgnoringCase("Invalid"));
        System.out.println("Validated error response for status code 400.");
    }

    // Validation for not found responses (status code 404)
    private void validateNotFoundResponse(Response response) {
        response.then().body("error", equalTo("Not Found"));
        response.then().body("message", containsStringIgnoringCase("Product not found"));
        System.out.println("Validated not found response for status code 404.");
    }

    // Validation for unprocessable entity responses (status code 422)
    private void validateUnprocessableEntityResponse(Response response) {
        response.then().body("error", equalTo("Unprocessable Entity"));
        response.then().body("details", notNullValue());
        System.out.println("Validated unprocessable entity response for status code 422.");
    }
}
