// ********RoostGPT********
/*
Test generated by RoostGPT for test sampleRESTtest using AI Type Azure Open AI and AI Model roostgpt-4-32k

Test generated for /products/{productId}_delete for http method type DELETE in rest-assured framework

RoostTestHash=9de2306488

[
  {
    "ScenarioID": "1",
    "TestName": "testValidRequestReturns200",
    "Description": "Test a valid DELETE request with a proper productId path parameter",
    "Execution": {
      "Arrange": "Prepare a valid integer productId path parameter",
      "Act": "Send DELETE request to /products/{productId} with a valid productId",
      "Assert": "Check for 200 status and response payload indicates successful deletion"
    },
    "Validation": "Ensures API correctly deletes a product when the request is valid"
  },
  {
    "ScenarioID": "2",
    "TestName": "testProductNotFoundReturns404",
    "Description": "Test the DELETE endpoint with a productId that does not exist",
    "Execution": {
      "Arrange": "Prepare a non-existent productId",
      "Act": "Send DELETE request to /products/{productId} with a non-existent productId",
      "Assert": "Check for 404 status and verify an appropriate error message in the response"
    },
    "Validation": "Ensures API correctly handles requests for non-existent products"
  },
  {
    "ScenarioID": "3",
    "TestName": "testMissingPathParameterReturnsError",
    "Description": "Test the DELETE endpoint with a missing productId path parameter",
    "Execution": {
      "Arrange": "Do not include the productId in the request path",
      "Act": "Send DELETE request to /products/ without a productId",
      "Assert": "Check for 404 status or appropriate error indicating missing path parameter"
    },
    "Validation": "Ensures API returns an error when the required productId path parameter is missing"
  },
  {
    "ScenarioID": "4",
    "TestName": "testInvalidPathParameterTypeReturnsError",
    "Description": "Test the DELETE endpoint with a non-integer productId",
    "Execution": {
      "Arrange": "Prepare a productId with an invalid type, e.g., string instead of integer",
      "Act": "Send DELETE request to /products/{productId} with a string productId",
      "Assert": "Check for 404 status or appropriate error message indicating invalid type for path parameter"
    },
    "Validation": "Ensures API handles type mismatch for path parameter gracefully"
  },
  {
    "ScenarioID": "5",
    "TestName": "testNullPathParameterReturnsError",
    "Description": "Test the DELETE endpoint with a null productId path parameter",
    "Execution": {
      "Arrange": "Prepare a request with a null value for the productId parameter",
      "Act": "Send DELETE request to /products/{productId} with null as the productId",
      "Assert": "Check for 404 status or appropriate error indicating invalid value for path parameter"
    },
    "Validation": "Ensures API returns an error when null value is provided for path parameter"
  },
  {
    "ScenarioID": "6",
    "TestName": "testMalformedPathParameterReturnsError",
    "Description": "Test the DELETE endpoint with a malformed productId value",
    "Execution": {
      "Arrange": "Prepare a malformed productId, e.g., special characters or mixed types",
      "Act": "Send DELETE request to /products/{productId} with malformed productId",
      "Assert": "Check for 404 status or appropriate error message indicating malformed path parameter"
    },
    "Validation": "Ensures API handles malformed path parameters appropriately"
  },
  {
    "ScenarioID": "7",
    "TestName": "testValidRequestWithLargeProductIdEdgeCase",
    "Description": "Test the DELETE endpoint with a productId close to the upper limit of int64",
    "Execution": {
      "Arrange": "Prepare a valid productId with a large integer value (e.g., 9223372036854775807)",
      "Act": "Send DELETE request to /products/{productId} with a large valid productId",
      "Assert": "Check for 200 status and response payload indicates successful deletion or appropriate handling"
    },
    "Validation": "Ensures API handles large integer input values correctly"
  },
  {
    "ScenarioID": "8",
    "TestName": "testValidRequestWithSmallProductIdEdgeCase",
    "Description": "Test the DELETE endpoint with a productId close to the lower limit of allowed values",
    "Execution": {
      "Arrange": "Prepare a valid small integer productId (e.g., 1)",
      "Act": "Send DELETE request to /products/{productId} with a small valid productId",
      "Assert": "Check for 200 status and response payload indicates successful deletion or appropriate handling"
    },
    "Validation": "Ensures API handles small integer input values correctly"
  },
  {
    "ScenarioID": "9",
    "TestName": "testNegativeProductIdReturnsError",
    "Description": "Test the DELETE endpoint with a negative integer for productId",
    "Execution": {
      "Arrange": "Prepare a negative integer productId (e.g., -1)",
      "Act": "Send DELETE request to /products/{productId} with a negative productId",
      "Assert": "Check for 404 status or appropriate error message indicating invalid path parameter"
    },
    "Validation": "Ensures API correctly handles negative integers as input for path parameters"
  },
  {
    "ScenarioID": "10",
    "TestName": "testEmptyPathParameterReturnsError",
    "Description": "Test the DELETE endpoint with an empty productId",
    "Execution": {
      "Arrange": "Prepare an empty value for the productId parameter in the path",
      "Act": "Send DELETE request to /products/{productId} with empty productId",
      "Assert": "Check for 404 status or appropriate error message indicating missing/invalid path parameter"
    },
    "Validation": "Ensures API correctly handles missing or empty path parameters"
  }
]

*/

// ********RoostGPT********
package com.bootexample4.RoostTest;

import io.restassured.RestAssured;
import io.restassured.response.Response;
import org.json.JSONArray;
import org.json.JSONObject;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;

import static io.restassured.RestAssured.given;
import static org.hamcrest.Matchers.equalTo;
import static org.hamcrest.Matchers.notNullValue;
import static org.hamcrest.MatcherAssert.assertThat;

/**
 * ProductsProductIdDeleteTest:
 * Tests various scenarios for DELETE requests to the /products/{productId} endpoint.
 */
public class ProductsProductIdDeleteTest {

    private List<JSONObject> testCases;

    @BeforeEach
    public void setUp() {
        // Load test cases from the JSON file
        TestdataLoader dataloader = new TestdataLoader();
        testCases = dataloader.loadJson("src\\test\\java\\com\\bootexample4\\RoostTest\\products_productIdDeleteTest.JSON");
        RestAssured.baseURI = "http://52.66.106.18:8080/api"; // Base URI for API requests
    }

    /**
     * Main Test Runner:
     * Iterates through test cases, constructs requests, sends them, and validates responses.
     */
    @Test
    public void ProductsProductIdDelete_Test() {
        Integer testNumber = 1;

        for (JSONObject testData : testCases) {
            String requestPath = "/products/{productId}";
            JSONObject pathParams = testData.optJSONObject("path_params");
            if (pathParams != null) {
                for (String key : pathParams.keySet()) {
                    requestPath = requestPath.replace("{" + key + "}", pathParams.getString(key));
                }
            }

            // Prepare the request specification
            io.restassured.specification.RequestSpecification req = given();
            configureHeaders(req, testData.optJSONObject("request_header"));
            configureQueryParams(req, testData.optJSONObject("query_params"));
            configureBody(req, testData.optJSONObject("request_body"));

            // Send DELETE request and extract response
            Response response = req.when().delete(requestPath).then().extract().response();

            // Log the test details
            System.out.printf("\nTest Case %d: %s\n", testNumber++, testData.optString("test_name", "Unnamed Test"));
            System.out.printf("Request: DELETE %s\n", requestPath);
            System.out.printf("Status Code: %d\n", response.statusCode());

            // Validate response based on the expected status code and scenario
            validateResponse(response, testData);
        }
    }

    /**
     * Helper Function: Configures headers for the request.
     */
    private void configureHeaders(io.restassured.specification.RequestSpecification req, JSONObject requestHeader) {
        String resolvedAuthToken = System.getenv("AUTH_TOKEN");
        if (requestHeader != null) {
            Iterator<String> keys = requestHeader.keys();
            while (keys.hasNext()) {
                String key = keys.next();
                String value = requestHeader.getString(key);

                if (key.equalsIgnoreCase("Authorization") && "${AUTH_TOKEN}".equalsIgnoreCase(value)) {
                    req.header("Authorization", "Bearer " + resolvedAuthToken);
                } else {
                    req.header(key, value);
                }
            }
        }

        // Add Authorization header if not explicitly set in the test case
        if (!req.getHeaders().hasHeaderWithName("Authorization") && resolvedAuthToken != null) {
            req.header("Authorization", "Bearer " + resolvedAuthToken);
        }
    }

    /**
     * Helper Function: Adds query parameters to the request.
     */
    private void configureQueryParams(io.restassured.specification.RequestSpecification req, JSONObject queryParams) {
        if (queryParams != null) {
            for (String key : queryParams.keySet()) {
                req.queryParam(key, queryParams.get(key));
            }
        }
    }

    /**
     * Helper Function: Configures the body of the request.
     */
    private void configureBody(io.restassured.specification.RequestSpecification req, JSONObject requestBody) {
        if (requestBody != null && requestBody.length() > 0) {
            req.body(requestBody.toString());
        }
    }

    /**
     * Validates the response based on the test case.
     */
    private void validateResponse(Response response, JSONObject testData) {
        int expectedStatusCode = testData.optInt("expected_status_code", 0);

        assertThat(
                "Expected status code " + expectedStatusCode + " but got " + response.statusCode(),
                response.statusCode(),
                equalTo(expectedStatusCode)
        );

        if (expectedStatusCode == 200) {
            validateSuccessResponse(response);
        } else if (expectedStatusCode == 404) {
            validateNotFoundResponse(response);
        } else if (expectedStatusCode == 400) {
            validateErrorResponse(response);
        } else if (expectedStatusCode == 422) {
            validateUnprocessableEntityResponse(response);
        } else {
            throw new IllegalArgumentException("Unexpected status code: " + expectedStatusCode);
        }
    }

    /**
     * Validates a 200 response indicating successful deletion.
     */
    private void validateSuccessResponse(Response response) {
        assertThat(response.jsonPath().getBoolean("success"), equalTo(true));
        assertThat(response.jsonPath().getString("message"), notNullValue());
        assertThat(response.jsonPath().getString("deletedProductId"), notNullValue());
    }

    /**
     * Validates a 404 response for product not found.
     */
    private void validateNotFoundResponse(Response response) {
        assertThat(response.jsonPath().getString("error"), equalTo("Product not found"));
        assertThat(response.jsonPath().getString("message"), notNullValue());
    }

    /**
     * Validates a 400 error response for bad requests.
     */
    private void validateErrorResponse(Response response) {
        assertThat(response.jsonPath().getString("error"), equalTo("Bad Request"));
        assertThat(response.jsonPath().getString("message"), notNullValue());
    }

    /**
     * Validates a 422 response for unprocessable entity.
     */
    private void validateUnprocessableEntityResponse(Response response) {
        assertThat(response.jsonPath().getString("error"), equalTo("Unprocessable Entity"));
        assertThat(response.jsonPath().getString("message"), notNullValue());
    }
}
