// ********RoostGPT********
/*
Test generated by RoostGPT for test sampleRESTtest using AI Type Azure Open AI and AI Model roostgpt-4-32k

Test generated for /products_post for http method type POST in rest-assured framework

RoostTestHash=c4679418bc


*/

// ********RoostGPT********
package com.bootexample4.RoostTest;

import io.restassured.RestAssured;
import io.restassured.path.json.JsonPath;
import io.restassured.http.ContentType;
import io.restassured.response.Response;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import java.util.*;

import static io.restassured.RestAssured.given;
import static org.hamcrest.Matchers.equalTo;
import static org.hamcrest.Matchers.is;
import static org.hamcrest.MatcherAssert.assertThat;

public class ProductsPostTest {

    List<Map<String, String>> envList = new ArrayList<>();

    @BeforeEach
    public void setUp() {
        TestDataLoader dataLoader = new TestDataLoader();
        envList = dataLoader.load("src\\test\\java\\com\\bootexample4\\RoostTest\\productsPostTest.csv");
    }

    @Test
    public void productsPost_Test() {
        setUp();
        int testNumber = 1;

        for (Map<String, String> testData : envList) {
            RestAssured.baseURI = Objects.requireNonNullElse(testData.get("nnnn_BASE_URL"), "http://52.66.106.18:8080/api");

            String requestBodyJson = testData.getOrDefault("RequestBody", "{}");
            Response response = given()
                    .contentType(ContentType.JSON)
                    .body(requestBodyJson)
                    .when()
                    .post("/products")
                    .then()
                    .extract()
                    .response();

            validateResponseType(response);
            validateStatusCode(response.statusCode(), testData);
            validateResponseBody(response.jsonPath());

            System.out.printf("Test Case %d: productsPost_Test \n", testNumber++);
            System.out.println("Request: POST /products");
            System.out.println("Status Code: " + response.statusCode());
        }
    }

    private void validateResponseType(Response response) {
        String contentType = response.getContentType();
        assertThat(contentType, is("application/json; charset=UTF-8"));
    }

    private void validateStatusCode(int actualStatusCode, Map<String, String> testData) {
        String expectedStatusCode = testData.get("statusCode");

        if (expectedStatusCode != null) {
            if (expectedStatusCode.contains("X")) {
                String actualStatusCodePrefix = String.valueOf(actualStatusCode).charAt(0);
                assertThat(actualStatusCodePrefix, equalTo(expectedStatusCode.charAt(0)));
            } else {
                assertThat(actualStatusCode, equalTo(Integer.parseInt(expectedStatusCode)));
            }
        } else {
            List<Integer> expectedStatusCodes = Arrays.asList(200, 405);
            assertThat(actualStatusCode, isIn(expectedStatusCodes));
        }
    }

    private void validateResponseBody(JsonPath response) {
        if (response.get("id") != null) {
            assertThat(response.get("id"), is(instanceOf(Integer.class)));
        }

        if (response.get("name") != null) {
            assertThat(response.get("name"), is(instanceOf(String.class)));
        }

        if (response.get("description") != null) {
            assertThat(response.get("description"), is(instanceOf(String.class)));
        }

        if (response.get("price") != null) {
            assertThat(response.get("price"), is(instanceOf(Integer.class)));
        }
    }
}
