// ********RoostGPT********
/*
Test generated by RoostGPT for test sampleRESTtest using AI Type Azure Open AI and AI Model roostgpt-4-32k

Test generated for /products_post for http method type POST in rest-assured framework

RoostTestHash=3f231531c5

[
  {
    "ScenarioID": "1",
    "TestName": "testValidProductCreation",
    "Description": "Test adding a new product with valid input data",
    "Execution": {
      "Arrange": "Create a valid request body: {\"name\": \"apple\", \"description\": \"fresh fruit\", \"price\": 20}",
      "Act": "Send POST request to /products with body",
      "Assert": "Check for 200 status and verify the response contains the product ID and matching details"
    },
    "Validation": "Ensures valid product creation with all required and optional fields"
  },
  {
    "ScenarioID": "2",
    "TestName": "testMissingRequiredField",
    "Description": "Test adding a product where the required 'name' field is missing",
    "Execution": {
      "Arrange": "Create a request body: {\"description\": \"fresh fruit\", \"price\": 20}",
      "Act": "Send POST request to /products with body",
      "Assert": "Check for 405 status and verify error message about missing 'name' field"
    },
    "Validation": "Ensures proper error handling when the required field 'name' is missing"
  },
  {
    "ScenarioID": "3",
    "TestName": "testEmptyRequestBody",
    "Description": "Test adding a product with an empty request body",
    "Execution": {
      "Arrange": "Prepare an empty JSON object as request body: {}",
      "Act": "Send POST request to /products with empty body",
      "Assert": "Check for 405 status and verify error message indicating no data provided"
    },
    "Validation": "Ensures API rejects product creation with an empty request body"
  },
  {
    "ScenarioID": "4",
    "TestName": "testInvalidPriceType",
    "Description": "Test adding a product with an invalid 'price' type (non-integer)",
    "Execution": {
      "Arrange": "Create a request body: {\"name\": \"banana\", \"description\": \"yellow fruit\", \"price\": \"twenty\"}",
      "Act": "Send POST request to /products with body",
      "Assert": "Check for 405 status and verify error message about invalid 'price' type"
    },
    "Validation": "Ensures proper error handling when 'price' is not an integer"
  },
  {
    "ScenarioID": "5",
    "TestName": "testExtraFieldsInRequestBody",
    "Description": "Test adding a product with extra unexpected fields in the request body",
    "Execution": {
      "Arrange": "Create a request body: {\"name\": \"pear\", \"description\": \"green fruit\", \"price\": 15, \"origin\": \"USA\"}",
      "Act": "Send POST request to /products with body",
      "Assert": "Check for 200 status and ensure extra fields are ignored and valid response is returned"
    },
    "Validation": "Ensures API handles extra fields gracefully and still processes valid input correctly"
  },
  {
    "ScenarioID": "6",
    "TestName": "testNegativePriceValue",
    "Description": "Test adding a product with a negative 'price' value",
    "Execution": {
      "Arrange": "Create a request body: {\"name\": \"grape\", \"description\": \"purple fruit\", \"price\": -10}",
      "Act": "Send POST request to /products with body",
      "Assert": "Check for 405 status and verify error message about invalid 'price' value"
    },
    "Validation": "Ensures API rejects product creation with invalid negative price value"
  },
  {
    "ScenarioID": "7",
    "TestName": "testNullNameField",
    "Description": "Test adding a product with 'name' field set to null",
    "Execution": {
      "Arrange": "Create a request body: {\"name\": null, \"description\": \"fruit\", \"price\": 10}",
      "Act": "Send POST request to /products with body",
      "Assert": "Check for 405 status and verify error message indicating 'name' cannot be null"
    },
    "Validation": "Ensures API validates null values for required fields"
  },
  {
    "ScenarioID": "8",
    "TestName": "testSpecialCharactersInName",
    "Description": "Test adding a product with special characters in 'name'",
    "Execution": {
      "Arrange": "Create a request body: {\"name\": \"appl@123\", \"description\": \"special name\", \"price\": 30}",
      "Act": "Send POST request to /products with body",
      "Assert": "Check for 200 status and verify the response correctly processes special characters"
    },
    "Validation": "Ensures API accepts special characters in 'name' field"
  },
  {
    "ScenarioID": "9",
    "TestName": "testNoRequestBody",
    "Description": "Test adding a product without sending a request body (null body)",
    "Execution": {
      "Arrange": "Prepare no body in the request",
      "Act": "Send POST request to /products with no body",
      "Assert": "Check for 405 status and verify error message indicating missing request body"
    },
    "Validation": "Ensures API rejects requests without a body"
  },
  {
    "ScenarioID": "10",
    "TestName": "testInvalidEndpoint",
    "Description": "Test sending a POST request to an invalid endpoint related to products",
    "Execution": {
      "Arrange": "Prepare a valid request body: {\"name\": \"apple\", \"description\": \"fruit\", \"price\": 20}",
      "Act": "Send POST request to /product (typo in endpoint)",
      "Assert": "Check for 404 status and verify error message for invalid endpoint"
    },
    "Validation": "Ensures proper handling for requests sent to incorrect endpoints"
  }
]

*/

// ********RoostGPT********
package com.bootexample4.RoostTest;

import org.json.JSONObject;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import io.restassured.RestAssured;
import io.restassured.response.Response;
import io.restassured.path.json.JsonPath;
import io.restassured.specification.RequestSpecification;
import java.util.*;
import static io.restassured.RestAssured.given;
import static org.hamcrest.Matchers.*;
import org.hamcrest.MatcherAssert;

public class ProductsPostTest {

    private List<JSONObject> testCases;

    /**
     * Set up test cases by loading them from a JSON file using `TestdataLoader`.
     * The JSON file contains various test scenarios in structured format.
     */
    @BeforeEach
    public void setUp() {
        TestdataLoader dataloader = new TestdataLoader();
        testCases = dataloader.loadJson("src/test/java/com/bootexample4/RoostTest/productsPostTest.JSON");
    }

    /**
     * Main test method to iterate through all scenarios, send POST requests, 
     * and verify responses.
     */
    @Test
    public void ProductsPost_Test() {
        // Initialize base URI for the API
        RestAssured.baseURI = "http://52.66.106.18:8080/api";
        int testNumber = 1;

        for (JSONObject testData : testCases) {
            String requestPath = buildRequestPath(testData);
            RequestSpecification req = buildRequestSpecification(testData);

            // Execute the POST request
            Response response = req.post(requestPath).then().extract().response();

            System.out.printf("Test Case %d: %s\n", testNumber++, testData.optString("TestName", "Unnamed Test"));
            System.out.println("Request Path: " + requestPath);
            System.out.println("Status Code: " + response.statusCode());

            validateResponse(testData, response); // Validate based on scenario expectations
        }
    }

    /**
     * Helper method to dynamically build the request path, replacing path parameters
     * in the specified endpoint string.
     * @param testData The test case data containing path parameters.
     * @return The resolved request path.
     */
    private String buildRequestPath(JSONObject testData) {
        String requestPath = testData.optString("request_path", "/products");
        JSONObject pathParams = testData.optJSONObject("path_params");

        if (pathParams != null) {
            for (String key : pathParams.keySet()) {
                requestPath = requestPath.replace("{" + key + "}", pathParams.getString(key));
            }
        }

        return requestPath;
    }

    /**
     * Helper method to construct the Rest Assured RequestSpecification with
     * headers, query parameters, and request body dynamically based on test data.
     * @param testData The test case data containing headers, query parameters, and body.
     * @return The constructed RequestSpecification.
     */
    private RequestSpecification buildRequestSpecification(JSONObject testData) {
        RequestSpecification req = given();

        // Add headers, resolving placeholders like "${AUTH_TOKEN}"
        JSONObject headers = testData.optJSONObject("request_header");
        if (headers != null) {
            addHeaders(req, headers);
        } else {
            addAuthorizationHeader(req); // Default authorization if header is missing
        }

        // Add query parameters if present
        JSONObject queryParams = testData.optJSONObject("query_params");
        if (queryParams != null) {
            queryParams.keySet().forEach(key -> req.queryParam(key, queryParams.get(key)));
        }

        // Add request body if present
        JSONObject requestBody = testData.optJSONObject("request_body");
        if (requestBody != null && requestBody.length() > 0) {
            req.body(requestBody.toString());
        }

        return req;
    }

    /**
     * Helper method to add headers to the RequestSpecification.
     * Resolves the "Authorization" header using environment variables or placeholders.
     * @param req The RequestSpecification.
     * @param headers The headers JSON object.
     */
    private void addHeaders(RequestSpecification req, JSONObject headers) {
        String userEnvAuthToken = System.getenv("AUTH_TOKEN");
        String resolvedAuthToken = (userEnvAuthToken != null && !userEnvAuthToken.isEmpty()) ? userEnvAuthToken : null;

        headers.keySet().forEach(key -> {
            String value = headers.getString(key);
            if (key.equalsIgnoreCase("Authorization") && value.equalsIgnoreCase("${AUTH_TOKEN}")) {
                req.header("Authorization", "Bearer " + resolvedAuthToken);
            } else {
                req.header(key, value);
            }
        });
    }

    /**
     * Helper method to add the "Authorization" header if no headers are specified.
     * @param req The RequestSpecification.
     */
    private void addAuthorizationHeader(RequestSpecification req) {
        String userEnvAuthToken = System.getenv("AUTH_TOKEN");
        if (userEnvAuthToken != null && !userEnvAuthToken.isEmpty()) {
            req.header("Authorization", "Bearer " + userEnvAuthToken);
        }
    }

    /**
     * Validates the API response based on expected status code and other criteria
     * defined in the test case data.
     * @param testData The test case data.
     * @param response The actual API response.
     */
    private void validateResponse(JSONObject testData, Response response) {
        int actualStatusCode = response.statusCode();
        int expectedStatusCode = testData.optInt("expected_status_code", 200);

        MatcherAssert.assertThat(
            "Expected status code " + expectedStatusCode + " but got " + actualStatusCode,
            actualStatusCode,
            equalTo(expectedStatusCode)
        );

        switch (actualStatusCode) {
            case 400 -> validateErrorResponse(response);
            case 404 -> validateNotFoundResponse(response);
            case 422 -> validateUnprocessableEntityResponse(response);
            case 200 -> validateSuccessResponse(testData, response);
        }
    }

    /**
     * Validates a 200 OK success response by checking response body elements.
     * @param testData The test case data.
     * @param response The actual API response.
     */
    private void validateSuccessResponse(JSONObject testData, Response response) {
        JsonPath jsonPath = response.jsonPath();
        JSONObject expectedBody = testData.optJSONObject("expected_body");

        // Validate product ID and other fields if expected body is provided
        if (expectedBody != null) {
            expectedBody.keySet().forEach(key -> 
                MatcherAssert.assertThat("Mismatch in field: " + key, 
                    jsonPath.get(key), 
                    equalTo(expectedBody.get(key)))
            );
        }
    }

    /**
     * Validates a 400 Bad Request error response.
     * @param response The actual API response.
     */
    private void validateErrorResponse(Response response) {
        response.then()
                .body("error", notNullValue())
                .body("message", containsString("Invalid input"));
    }

    /**
     * Validates a 404 Not Found error response.
     * @param response The actual API response.
     */
    private void validateNotFoundResponse(Response response) {
        response.then()
                .body("error", equalTo("Not Found"))
                .body("message", containsString("Endpoint does not exist"));
    }

    /**
     * Validates a 422 Unprocessable Entity error response.
     * @param response The actual API response.
     */
    private void validateUnprocessableEntityResponse(Response response) {
        response.then()
                .body("error", notNullValue())
                .body("message", containsString("Malformed request"));
    }
}
