// ********RoostGPT********
/*
Test generated by RoostGPT for test sampleRESTtest using AI Type Azure Open AI and AI Model roostgpt-4-32k

Test generated for /products_get for http method type GET in rest-assured framework

RoostTestHash=4935a0d04b

[
  {
    "ScenarioID": "1",
    "TestName": "testValidRequestReturns200",
    "Description": "Test a valid GET request with correct endpoint",
    "Execution": {
      "Arrange": "Prepare request with no parameters",
      "Act": "Send GET request to /products endpoint",
      "Assert": "Verify response status is 200 and response body contains list of products"
    },
    "Validation": "Ensures successful operation and response format includes expected product details"
  },
  {
    "ScenarioID": "2",
    "TestName": "testResponseContentValidation",
    "Description": "Test that response contains required fields in product schema",
    "Execution": {
      "Arrange": "Prepare the request with default settings",
      "Act": "Send GET request to /products endpoint",
      "Assert": "Validate that response contains required fields 'id', 'name', 'description', and 'price' that match their types"
    },
    "Validation": "Ensures API response adheres to expected schema definition"
  },
  {
    "ScenarioID": "3",
    "TestName": "testEmptyResponseBodyOnNoProducts",
    "Description": "Test when no products are available the response is empty",
    "Execution": {
      "Arrange": "Ensure no products exist in the database (mock setup)",
      "Act": "Send GET request to /products endpoint",
      "Assert": "Verify response status is 200 and the response body is an empty array"
    },
    "Validation": "Ensures API behaves correctly when no data is available"
  },
  {
    "ScenarioID": "4",
    "TestName": "testInvalidMethodReturns405",
    "Description": "Test that using an unsupported HTTP method returns status 405",
    "Execution": {
      "Arrange": "Prepare a POST request to /products endpoint",
      "Act": "Send POST request to /products endpoint",
      "Assert": "Verify response status is 405 and response contains a helpful error message"
    },
    "Validation": "Ensures endpoints reject unsupported HTTP methods"
  },
  {
    "ScenarioID": "5",
    "TestName": "testMalformedURLReturns404",
    "Description": "Test that a request to a malformed URL returns status 404",
    "Execution": {
      "Arrange": "Prepare GET request to /product instead of /products",
      "Act": "Send GET request to /product endpoint",
      "Assert": "Verify response status is 404 and response contains appropriate error message"
    },
    "Validation": "Ensures API correctly handles invalid endpoint URLs"
  },
  {
    "ScenarioID": "6",
    "TestName": "testLargePayloadHandling",
    "Description": "Test response when large data is returned",
    "Execution": {
      "Arrange": "Mock a database response with a large number of products",
      "Act": "Send GET request to /products endpoint",
      "Assert": "Verify response status is 200 and all products are returned correctly"
    },
    "Validation": "Ensures API can handle large responses efficiently"
  },
  {
    "ScenarioID": "7",
    "TestName": "testNonJSONResponseHandling",
    "Description": "Test that API rejects non-JSON acceptable headers",
    "Execution": {
      "Arrange": "Prepare GET request with Accept header set to 'text/plain'",
      "Act": "Send GET request to /products endpoint",
      "Assert": "Verify response status is 406 and response includes proper error message"
    },
    "Validation": "Ensures API properly enforces JSON response format requirements"
  },
  {
    "ScenarioID": "8",
    "TestName": "testDuplicateProductHandling",
    "Description": "Test API behavior when duplicate products exist",
    "Execution": {
      "Arrange": "Mock a database response with duplicate products",
      "Act": "Send GET request to /products endpoint",
      "Assert": "Verify response status is 200 and each product appears only once"
    },
    "Validation": "Ensures API handles duplicate records gracefully"
  },
  {
    "ScenarioID": "9",
    "TestName": "testExistingProductsWithOutOfBoundsPrice",
    "Description": "Test API response when products with unrealistic price values exist",
    "Execution": {
      "Arrange": "Mock a database with products having negative price values or extremely high prices",
      "Act": "Send GET request to /products endpoint",
      "Assert": "Verify response status is 200 and response contains appropriate data, without breaking API functionality"
    },
    "Validation": "Ensures API robustness regardless of irregular data in the database"
  },
  {
    "ScenarioID": "10",
    "TestName": "testNullResponseFields",
    "Description": "Test response behavior when product fields contain null values",
    "Execution": {
      "Arrange": "Mock a database with products having null values in 'description' or 'price'",
      "Act": "Send GET request to /products endpoint",
      "Assert": "Verify response status is 200 and null values are handled correctly"
    },
    "Validation": "Ensures API can manage data with null fields while adhering to schema"
  }
]

*/

// ********RoostGPT********
package com.bootexample4.RoostTest;

import org.json.JSONObject;
import org.json.JSONArray;
import io.restassured.RestAssured;
import io.restassured.response.Response;
import io.restassured.path.json.JsonPath;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import java.util.*;
import static io.restassured.RestAssured.given;
import static org.hamcrest.Matchers.*;
import org.hamcrest.MatcherAssert;

public class ProductsGetTest {

    // List to hold test cases loaded from the JSON file
    private List<JSONObject> testCases = new ArrayList<>();

    /**
     * Sets up the test data for each test execution.
     * Loads JSON test data from a predefined location.
     */
    @BeforeEach
    public void setUp() {
        TestdataLoader dataloader = new TestdataLoader();
        testCases = dataloader.loadJson("src\\test\\java\\com\\bootexample4\\RoostTest\\productsGetTest.JSON");
    }

    /**
     * Main test method to execute scenarios defined in the JSON file.
     * Ensures correct request preparation, response validation, and logging.
     */
    @Test
    public void executeProductsGetTests() {
        setUp();
        int testCounter = 1;

        RestAssured.baseURI = "http://52.66.106.18:8080/api";

        for (JSONObject testData : testCases) {
            System.out.printf("\n--- Executing Test Case %d: ---\n", testCounter);

            // Prepare request specifications
            String requestPath = buildRequestPath(testData.optJSONObject("path_params"), "/products");
            io.restassured.specification.RequestSpecification reqSpec = prepareRequest(testData);

            // Determine HTTP method (assuming GET for simplicity; extendable for other methods)
            String method = testData.has("method") ? testData.getString("method").toLowerCase() : "get";

            // Execute the request
            Response response = executeRequest(reqSpec, method, requestPath);

            // Validate response
            System.out.println("Request Path: " + requestPath);
            System.out.println("HTTP Status Code: " + response.statusCode());
            validateResponse(response, testData);

            testCounter++;
        }
    }

    /**
     * Constructs the request path, replacing path parameters dynamically.
     *
     * @param pathParams The path parameters JSON object.
     * @param basePath   The base API path.
     * @return The final constructed request path.
     */
    private String buildRequestPath(JSONObject pathParams, String basePath) {
        if (pathParams != null) {
            for (String key : pathParams.keySet()) {
                basePath = basePath.replace("{" + key + "}", pathParams.getString(key));
            }
        }
        return basePath;
    }

    /**
     * Prepares the Rest Assured Request Specification by setting headers, query parameters, and body.
     *
     * @param testData The test data for the current test case.
     * @return Configured Request Specification.
     */
    private io.restassured.specification.RequestSpecification prepareRequest(JSONObject testData) {
        io.restassured.specification.RequestSpecification spec = given();

        // Set headers, including dynamic resolution of Authorization token
        JSONObject requestHeader = testData.optJSONObject("request_header");
        String authToken = resolveAuthToken();
        if (requestHeader != null) {
            for (String headerKey : requestHeader.keySet()) {
                String headerValue = requestHeader.getString(headerKey);
                if (headerKey.equalsIgnoreCase("Authorization") && headerValue.equals("${AUTH_TOKEN}")) {
                    spec.header(headerKey, "Bearer " + authToken);
                } else {
                    spec.header(headerKey, headerValue);
                }
            }
        } else if (authToken != null) {
            spec.header("Authorization", "Bearer " + authToken);
        }

        // Set query parameters
        JSONObject queryParams = testData.optJSONObject("query_params");
        if (queryParams != null) {
            for (String paramKey : queryParams.keySet()) {
                spec.queryParam(paramKey, queryParams.get(paramKey));
            }
        }

        // Set request body
        JSONObject requestBody = testData.optJSONObject("request_body");
        if (requestBody != null && requestBody.length() > 0) {
            spec.body(requestBody.toString());
        }

        return spec;
    }

    /**
     * Resolves the Authorization token, prioritizing environment variables, followed by test data defaults.
     *
     * @return Authorization token string.
     */
    private String resolveAuthToken() {
        String envAuthToken = System.getenv("AUTH_TOKEN");
        return (envAuthToken != null && !envAuthToken.isEmpty()) ? envAuthToken : "defaultAuthToken";
    }

    /**
     * Executes the HTTP request based on the method and path provided.
     *
     * @param reqSpec     The Request Specification.
     * @param method      The HTTP method (GET, POST, etc.).
     * @param requestPath The target endpoint path.
     * @return Response object.
     */
    private Response executeRequest(io.restassured.specification.RequestSpecification reqSpec, String method, String requestPath) {
        switch (method.toLowerCase()) {
            case "post":
                return reqSpec.when().post(requestPath).then().extract().response();
            case "get":
                return reqSpec.when().get(requestPath).then().extract().response();
            case "put":
                return reqSpec.when().put(requestPath).then().extract().response();
            case "delete":
                return reqSpec.when().delete(requestPath).then().extract().response();
            default:
                throw new RuntimeException("Unsupported HTTP method: " + method);
        }
    }

    /**
     * Validates the response against expected status codes and schemas as per test data.
     *
     * @param response The Response object.
     * @param testData The test data defining validations.
     */
    private void validateResponse(Response response, JSONObject testData) {
        int actualStatusCode = response.statusCode();

        if (testData.has("expected_status_code")) {
            int expectedStatusCode = testData.getInt("expected_status_code");
            MatcherAssert.assertThat(
                    "Expected status code " + expectedStatusCode + " but got " + actualStatusCode,
                    actualStatusCode,
                    equalTo(expectedStatusCode)
            );

            // Use error response validation methods if applicable
            if (actualStatusCode == 400) validateErrorResponse(response);
            if (actualStatusCode == 404) validateNotFoundResponse(response);
            if (actualStatusCode == 422) validateUnprocessableEntityResponse(response);
        }
    }

    /**
     * Validates responses with HTTP status 400 (Bad Request).
     *
     * @param response The Response object.
     */
    private void validateErrorResponse(Response response) {
        response.then().assertThat()
                .body("error", notNullValue())
                .body("message", containsString("Invalid request"))
                .statusCode(400);
    }

    /**
     * Validates responses with HTTP status 404 (Not Found).
     *
     * @param response The Response object.
     */
    private void validateNotFoundResponse(Response response) {
        response.then().assertThat()
                .body("error", notNullValue())
                .body("message", containsString("Resource not found"))
                .statusCode(404);
    }

    /**
     * Validates responses with HTTP status 422 (Unprocessable Entity).
     *
     * @param response The Response object.
     */
    private void validateUnprocessableEntityResponse(Response response) {
        response.then().assertThat()
                .body("error", notNullValue())
                .body("message", containsString("Cannot process entity"))
                .statusCode(422);
    }
}
