// ********RoostGPT********
/*
Test generated by RoostGPT for test sampleRESTtest using AI Type Azure Open AI and AI Model roostgpt-4-32k

Test generated for /products/{productId}_put for http method type PUT in rest-assured framework

RoostTestHash=89ec8e0a9b


*/

// ********RoostGPT********

    --- Refactored Test Code Snippet Start ---
    
    package com.bootexample4.RoostTest;

    import io.restassured.RestAssured;
    import io.restassured.path.json.JsonPath;
    import io.restassured.response.Response;
    import org.junit.jupiter.api.BeforeEach;
    import org.junit.jupiter.api.Test;

    import java.util.ArrayList;
    import java.util.List;
    import java.util.Map;

    import static io.restassured.RestAssured.given;
    import static org.junit.Assert.assertThat;
    import static org.junit.Assert.fail;
    import static org.hamcrest.Matchers.*;

    public class ProductsProductIdPutTest {

        private List<Map<String, String>> envList = new ArrayList<>();
    
        @BeforeEach
        public void setUp() {
            TestdataLoader dataloader = new TestdataLoader();
            String[] envVarsList = {"productId"};
            envList = dataloader.load("src/test/java/com/bootexample4/RoostTest/products_productIdPutTest.csv", envVarsList);
        }
    
        @Test  
        public void productsProductIdPut_Test() {
            Integer testNumber = 1;
            for (Map<String, String> testData : envList) {
                String baseURL = testData.getOrDefault("nnnn_BASE_URL", "http://52.66.106.18:8080/api");
                String requestBody = testData.getOrDefault("RequestBody", "{}");

                Response response = given()
                    .baseUri(baseURL)
                    .contentType("application/json")
                    .body(requestBody)
                    .pathParam("productId", testData.getOrDefault("productId", ""))
                    .when()
                    .put("/products/{productId}")
                    .andReturn();
    
                int statusCode = response.statusCode();
                String contentType = response.contentType();
    
                System.out.printf("Test Case %d: productsProductIdPut_Test \n", testNumber++);
                System.out.println("Request: PUT /products/{productId}");
                System.out.println("Status Code: " + statusCode);
    
                validateStatusCode(testData, statusCode);
    
                if(contentType.contains("application/json")){
                    JsonPath jsonPathEvaluator = response.jsonPath();
                    validateJsonResponse(statusCode, jsonPathEvaluator);
                }else{
                    fail("Unsupported content type: " + contentType);
                }
            }
        }
    
        private void validateStatusCode(Map<String, String> testData, int statusCode) {
            int expectedStatusCode = testData.get("statusCode") != null ? Integer.parseInt(testData.get("statusCode")) : 200;
    
            assertThat(String.format("Expected a status code of %d", expectedStatusCode),
                statusCode, equalTo(expectedStatusCode));
        }
    
        private void validateJsonResponse(int statusCode, JsonPath jsonPathEvaluator) {
            switch(statusCode){
                case 200:
                    System.out.println("Description: Updated Product");
                    assertThat(jsonPathEvaluator.get("id"), instanceOf(Integer.class));
                    assertThat(jsonPathEvaluator.get("name"), instanceOf(String.class));
                    assertThat(jsonPathEvaluator.get("description"), instanceOf(String.class));
                    assertThat(jsonPathEvaluator.get("price"), instanceOf(Integer.class));
                    break;
                case 404:
                    System.out.println("Description: Not Found");
                    break;
                default:
                    fail("Unsupported status code: " + statusCode);
            }
        }
    }

    --- Refactored Test Code Snippet End ---