// ********RoostGPT********
/*
Test generated by RoostGPT for test sampleRESTtest using AI Type Open AI and AI Model gpt-4-turbo

Test generated for /products/{productId}_put for http method type PUT in rest-assured framework

RoostTestHash=89ec8e0a9b


*/

// ********RoostGPT********
package com.bootexample4.RoostTest;

import io.restassured.RestAssured;
import io.restassured.path.json.JsonPath;
import io.restassured.http.ContentType;
import io.restassured.response.Response;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static io.restassured.RestAssured.given;
import java.util.HashMap;
import java.util.Map;
import java.util.List;
import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.Matchers.*;
import org.json.JSONObject;
import org.json.XML;

public class ProductsProductIdPutTest {

    private List<Map<String, String>> envList;

    @BeforeEach
    public void setUp() {
        TestdataLoader dataloader = new TestdataLoader();
        String[] envVarsList = {"productId"};
        envList = dataloader.load("src/test/java/com/bootexample4/RoostTest/products_productIdPutTest.csv", envVarsList);
    }

    @Test
    public void productsProductIdPutTest() {
        Integer testNumber = 1;
        for (Map<String, String> testData : envList) {
            String baseUrl = testData.getOrDefault("nnnn_BASE_URL", "http://52.66.106.18:8080/api");
            RestAssured.baseURI = baseUrl;

            JSONObject requestBodyObject = new JSONObject(testData.getOrDefault("RequestBody", "{}"));
            Response response = given()
                    .pathParam("productId", testData.getOrDefault("productId", ""))
                    .contentType(ContentType.JSON)
                    .body(requestBodyObject.toString())
                    .when()
                    .put("/products/{productId}")
                    .then()
                    .extract().response();

            validateResponse(response, testData, testNumber++);
        }
    }

    private void validateResponse(Response response, Map<String, String> testData, Integer testNumber) {
        int statusCode = response.statusCode();
        String contentType = response.getContentType();

        System.out.printf("Test Case %d: productsProductIdPutTest \n", testNumber);
        System.out.println("Request: PUT /products/{productId}");
        System.out.println("Status Code: " + statusCode);

        validateStatusCode(response, testData);
        validateContentType(contentType);

        if (contentType.contains("application/json")) {
            validateJsonResponse(response.jsonPath(), statusCode);
        } else if (contentType.contains("application/xml") || contentType.contains("text/xml")) {
            validateXmlResponse(response.asString());
        } else {
            System.out.println("Unsupported content type: " + contentType);
        }
    }

    private void validateStatusCode(Response response, Map<String, String> testData) {
        String expectedStatusCode = testData.get("statusCode");
        if (expectedStatusCode != null) {
            if (expectedStatusCode.contains("X")) {
                assertThat("Status code does not match expected category",
                        String.valueOf(response.statusCode()).charAt(0), equalTo(expectedStatusCode.charAt(0)));
            } else {
                assertThat("Status code mismatch", response.statusCode(), equalTo(Integer.parseInt(expectedStatusCode)));
            }
        } else {
            List<Integer> expectedStatusCodes = List.of(200, 404);
            assertThat("Unexpected status code", response.statusCode(), is(in(expectedStatusCodes)));
        }
    }

    private void validateContentType(String contentType) {
        assertThat("Invalid content type", contentType, anyOf(containsString("application/json"), containsString("application/xml"), containsString("text/xml")));
    }

    private void validateJsonResponse(JsonPath response, int statusCode) {
        switch (statusCode) {
            case 200:
                System.out.println("Description: Updated Product");
                assertThat("Invalid ID type", response.get("id"), instanceOf(Integer.class));
                assertThat("Invalid name type", response.get("name"), instanceOf(String.class));
                assertThat("Invalid description type", response.get("description"), instanceOf(String.class));
                assertThat("Invalid price type", response.get("price"), instanceOf(Integer.class));
                break;
            case 404:
                validateNotFoundResponse(response);
                break;
            case 422:
                validateUnprocessableEntityResponse(response);
                break;
            default:
                break;
        }
    }

    private void validateXmlResponse(String xmlResponse) {
        JSONObject jsonResponse = XML.toJSONObject(xmlResponse);
        JsonPath response = new JsonPath(jsonResponse.toString());
        // Perform validations similar to JSON
    }

    private void validateNotFoundResponse(JsonPath response) {
        assertThat("Error message not found", response.get("message"), equalTo("Product not found"));
    }

    private void validateUnprocessableEntityResponse(JsonPath response) {
        assertThat("Error detail missing", response.get("details"), not(empty()));
    }
}
