// ********RoostGPT********
/*
Test generated by RoostGPT for test sampleRESTtest using AI Type Azure Open AI and AI Model roostgpt-4-32k

Test generated for /products_get for http method type GET in rest-assured framework

RoostTestHash=50b0ea8cc0


*/

// ********RoostGPT********
package com.bootexample4.RoostTest;

import io.restassured.RestAssured;
import io.restassured.path.json.JsonPath;
import io.restassured.response.Response;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static io.restassured.RestAssured.given;
import java.util.HashMap;
import java.util.Map;
import java.util.ArrayList;
import java.util.List;
import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.Matchers.*;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.json.JSONObject;
import org.json.XML;
import org.json.JSONException;

public class productsGetTest {

  private String defaultBaseUrl = "http://52.66.106.18:8080/api";
  private String resource = "/products";

  List<Map<String, String>> envList = new ArrayList<>();

  @BeforeEach
  public void setUp() {
    TestdataLoader dataloader = new TestdataLoader();
    String[] envVarsList = {""};
    envList = dataloader.load("src\\test\\java\\com\\bootexample4\\RoostTest\\productsGetTest.csv", envVarsList);
  }

  @Test
  public void productsGet_Test() throws JSONException {
    this.setUp();
    Integer testNumber = 1;
    for (Map<String, String> testData : envList) {
      String baseUrl = testData.getOrDefault("nnnn_BASE_URL", defaultBaseUrl);
      RestAssured.baseURI = baseUrl;

      Response response = given()
          .when()
          .get(resource)
          .then()
          .extract().response();

      JsonPath jsonResponse;
      String contentType = response.getContentType();
      int statusCode = response.statusCode();
      
      if (contentType.contains("application/xml")) {
        String xmlResponse = response.asString();
        JSONObject jsonResponseXML = XML.toJSONObject(xmlResponse);
        String jsonString = jsonResponseXML.toString();
        jsonResponse = new JsonPath(jsonString);
      } else if(contentType.contains("application/json")) {
        jsonResponse = response.jsonPath(); 
      } else {
        System.out.println("Unsupported Content Type.");
        continue;
      }

      // Status code verification
      if (statusCode == 200) {
        assertThat(contentType, equalTo("application/json"));
        
        // Field validation
        if (jsonResponse.get("id") != null) {
          assertThat(jsonResponse.get("id"), instanceOf(Integer.class));
        }

        if (jsonResponse.get("name") != null) {
          assertThat(jsonResponse.get("name"), instanceOf(String.class));
        }

        if (jsonResponse.get("description") != null) {
          assertThat(jsonResponse.get("description"), instanceOf(String.class));
        }

        if (jsonResponse.get("price") != null) {
          assertThat(jsonResponse.get("price"), instanceOf(Integer.class));
        }
      } else {
        // Define other case statements for handling different server codes as needed
        System.out.println("HTTP Status code: " + statusCode + " not handled.");
      }     
    }
  }
}
