// ********RoostGPT********
/*
Test generated by RoostGPT for test sampleRESTtest using AI Type Open AI and AI Model gpt-4-turbo

Test generated for /products/{productId}_delete for http method type DELETE in rest-assured framework

RoostTestHash=9de2306488


*/

// ********RoostGPT********
package com.bootexample4.RoostTest;

import io.restassured.RestAssured;
import io.restassured.path.json.JsonPath;
import io.restassured.response.Response;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static io.restassured.RestAssured.given;
import java.util.List;
import java.util.Map;
import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.Matchers.*;

public class ProductsProductIdDeleteTest {

    private List<Map<String, String>> environmentVariables;

    @BeforeEach
    public void setUp() {
        TestdataLoader dataLoader = new TestdataLoader();
        String[] envVarsList = {"productId"};
        environmentVariables = dataLoader.load("src/test/java/com/bootexample4/RoostTest/products_productIdDeleteTest.csv", envVarsList);
    }

    @Test
    public void productsProductIdDeleteTest() {
        int testNumber = 1;
        for (Map<String, String> testData : environmentVariables) {
            String baseUri = testData.getOrDefault("nnnn_BASE_URL", "http://52.66.106.18:8080/api");
            RestAssured.baseURI = baseUri;
            
            Response response = given()
                    .pathParam("productId", testData.getOrDefault("productId", ""))
                    .when()
                    .delete("/products/{productId}")
                    .then()
                    .extract().response();

            int statusCode = response.statusCode();
            String contentType = response.getContentType();
            JsonPath jsonPath = getJsonPathFromResponse(response, contentType);

            System.out.printf("Test Case %d: productsProductIdDeleteTest \n", testNumber++);
            System.out.println("Request: DELETE /products/{productId}");
            System.out.println("Status Code: " + statusCode);

            validateStatusCode(testData, statusCode);
            validateContentType(contentType);
            validateResponseByStatusCode(statusCode, jsonPath);
        }
    }

    private JsonPath getJsonPathFromResponse(Response response, String contentType) {
        if (contentType.contains("application/xml") || contentType.contains("text/xml")) {
            String xmlResponse = response.asString();
            return new JsonPath(XML.toJSONObject(xmlResponse).toString());
        } else if (contentType.contains("application/json")) {
            return response.jsonPath();
        } else {
            throw new IllegalArgumentException("Unsupported content type: " + contentType);
        }
    }

    private void validateStatusCode(Map<String, String> testData, int actualStatusCode) {
        String expectedStatusCode = testData.get("statusCode");
        if (expectedStatusCode != null) {
            if (expectedStatusCode.contains("X")) {
                assertThat("Status code category mismatch.", actualStatusCode / 100, equalTo(Integer.parseInt(expectedStatusCode.substring(0, 1))));
            } else {
                assertThat("Status code mismatch.", actualStatusCode, equalTo(Integer.parseInt(expectedStatusCode)));
            }
        } else {
            List<Integer> expectedStatusCodes = List.of(200, 404);
            assertThat("Unexpected status code.", actualStatusCode, is(in(expectedStatusCodes)));
        }
    }

    private void validateContentType(String contentType) {
        List<String> supportedTypes = List.of("application/json", "text/xml", "application/xml");
        assertThat("Unsupported content type: " + contentType, supportedTypes, hasItem(contentType));
    }

    private void validateResponseByStatusCode(int statusCode, JsonPath response) {
        if (statusCode == 200) {
            System.out.println("Description: Product deleted");
            // Additional validation can be implemented here
        } else if (statusCode == 404) {
            System.out.println("Description: Not Found");
            validateNotFoundResponse(response);
        } else if (statusCode == 422) {
            System.out.println("Description: Unprocessable Entity");
            validateUnprocessableEntityResponse(response);
        }
    }

    private void validateNotFoundResponse(JsonPath response) {
        assertThat("Error message mismatch.", response.getString("error"), equalTo("Product not found"));
    }

    private void validateUnprocessableEntityResponse(JsonPath response) {
        assertThat("Error detail is incorrect.", response.getString("error"), equalTo("Validation failed"));
    }
}
