# ********RoostGPT********

# Test generated by RoostGPT for test sampleKarateEnv using AI Type  and AI Model 
# 
# Feature file generated for /products_get for http method type GET 
# RoostTestHash=ed0d766b50
# 
# 

# ********RoostGPT********
Feature: Test the /products API for retrieving all products

  Background:
    * def urlBase = karate.properties['nnnn_URL_BASE'] || karate.get('urlBase', 'http://localhost:4010')
    * url urlBase
    * configure headers = { Authorization: #(karate.properties['nnnn_AUTH_TOKEN']) }

  Scenario: Get all products with successful response
    Given path '/products'
    When method get
    Then status 200
    And match response == { id: '#number', name: '#string', description: '#string', price: '#number' }
    And match response.id == '#number'
    And match response.name == '#string'
    And match response.description == '#string'
    And match response.price == '#number'
