# ********RoostGPT********

# Test generated by RoostGPT for test sampleKarateEnv using AI Type  and AI Model 
# 
# Feature file generated for /products/{productId}_put for http method type PUT 
# RoostTestHash=6762b8ac71
# 
# 

# ********RoostGPT********
Feature: Update a product in the store

  Background:
    * def urlBase = karate.properties['nnnn_URL_BASE'] || karate.get('urlBase', 'http://localhost:4010')
    * configure headers = { Authorization: #(karate.properties['nnnn_AUTH_TOKEN']) }

  Scenario Outline: Update product details
    Given url urlBase
    And path '/products/', <productId>
    And request
      """
      { 
        id: <id>, 
        name: <name>, 
        description: <description>, 
        price: <price> 
      }
      """
    When method PUT
    Then status <expectedStatus>
    And match response ==
      """
      { 
        id: '#(id)', 
        name: '#(name)', 
        description: '#(description)', 
        price: '#(price)' 
      }
      """

    Examples:
      | productId | id | name    | description            | price | expectedStatus |
      |         1 | 10 | 'apple' | 'description of apple' |    20 |            200 |
      |         2 | 11 | 'pear'  | 'description of pear'  |    30 |            200 |
      |       999 | 12 | 'grape' | 'description of grape' |    40 |            404 |

  Scenario: Update product with invalid data type
    Given url urlBase
    And path '/products/1'
    And request
      """
      { 
        id: 'string', 
        name: 'apple', 
        description: 'description of apple', 
        price: 20 
      }
      """
    When method PUT
    Then status 400

  Scenario: Update product without authentication
    * configure headers = {}
    Given url urlBase
    And path '/products/1'
    And request
      """
      { 
        id: 10, 
        name: 'apple', 
        description: 'description of apple', 
        price: 20 
      }
      """
    When method PUT
    Then status 401
