# ********RoostGPT********

# Test generated by RoostGPT for test sampleKarateEnv using AI Type Open AI and AI Model gpt-4-turbo
# 
# Feature file generated for /products_get for http method type GET 
# RoostTestHash=ed0d766b50
# 
# 

# ********RoostGPT********
Feature: Test suite for the /products API

  Background:
    * def urlBase = karate.properties['nnnn_URL_BASE'] || karate.get('urlBase', 'http://localhost:4010')
    * url urlBase
    * configure headers = { Authorization: #(karate.properties['nnnn_AUTH_TOKEN']) }

  Scenario: Verify GET request for all products
    Given path '/products'
    When method get
    Then status 200
    And match response ==
      """
      { 
        id: '#number', 
        name: '#string', 
        description: '#string', 
        price: '#number' 
      }
      """
    And match response contains
      """
      { 
        name: 'apple' 
      }
      """
