# ********RoostGPT********

# Test generated by RoostGPT for test sampleKarateEnv using AI Type  and AI Model 
# 
# Feature file generated for /products/{productId}_put for http method type PUT 
# RoostTestHash=6762b8ac71
# 
# 

# ********RoostGPT********
Feature: Update a product in the store

  Background:
    * def urlBase = karate.properties['nnnn_URL_BASE'] || karate.get('urlBase', 'http://localhost:4010')
    * configure headers = { Authorization: #(karate.properties['nnnn_AUTH_TOKEN']) }

  Scenario Outline: Update product details
    Given url urlBase
    And path '/products/', <productId>
    And request
      """
      {
        id: #(id),
        name: "<name>",
        description: "<description>",
        price: #(price)
      }
      """
    When method PUT
    Then status <expectedStatus>
    And match response
      """
      {
        id: #(id),
        name: "<name>",
        description: "<description>",
        price: #(price)
      }
      """

    Examples:
      | productId | id  | name    | description         | price | expectedStatus |
      |       101 | 101 | 'apple' | 'Fresh green apple' |   150 |            200 |
      |       102 | 102 | 'pear'  | 'Sweet juicy pear'  |   120 |            200 |
      |       999 | 999 | 'fig'   | 'Exotic dried fig'  |   300 |            404 |

  Scenario: Update product without authorization
    Given url urlBase
    And path '/products/101'
    And request
      """
      {
        id: 101,
        name: 'apple',
        description: 'Fresh green apple',
        price: 150
      }
      """
    * configure headers = {}
    When method PUT
    Then status 401

  Scenario: Update product with invalid data type
    Given url urlBase
    And path '/products/101'
    And request
      """
      {
        id: 'abc',
        name: 123,
        description: true,
        price: 'xyz'
      }
      """
    When method PUT
    Then status 400

  Scenario: Update product with missing required fields
    Given url urlBase
    And path '/products/101'
    And request
      """
      {
        description: 'Only description'
      }
      """
    When method PUT
    Then status 400
