# ********RoostGPT********

# Test generated by RoostGPT for test sampleKarateEnv using AI Type  and AI Model 
# 
# Feature file generated for /products_post for http method type POST 
# RoostTestHash=2c080099fd
# 
# 

# ********RoostGPT********
Feature: Product Management API

  Background:
    * def urlBase = karate.properties['nnnn_URL_BASE'] || karate.get('urlBase', 'http://localhost:4010')
    * url urlBase
    * configure headers = { Authorization: #(karate.properties['nnnn_AUTH_TOKEN']) }

  Scenario Outline: Add a new product to the store
    Given path '/products'
    And request
      """
      <body>
      """
    When method post
    Then status <status>
    And match response ==
      """
      <expectedResponse>
      """

    Examples:
      | body                                                                                     | status | expectedResponse                                                                         |
      | { "id": 10, "name": "apple", "description": "description of the product", "price": 20 }  |    200 | { "id": 10, "name": "apple", "description": "description of the product", "price": 20 }  |
      | { "id": 11, "name": "banana", "description": "fresh bananas from Ecuador", "price": 15 } |    200 | { "id": 11, "name": "banana", "description": "fresh bananas from Ecuador", "price": 15 } |
      | { "id": null, "name": "invalid product", "description": "no description", "price": 5 }   |    405 | { "error": "Invalid input" }                                                             |

  Scenario: Attempt to add a product with missing name
    Given path '/products'
    And request
      """
      { "id": 12, "description": "missing name", "price": 30 }
      """
    When method post
    Then status 405
    And match response ==
      """
      { "error": "Invalid input" }
      """
