# ********RoostGPT********

# Test generated by RoostGPT for test sampleKarateEnv using AI Type  and AI Model 
# 
# Feature file generated for /products/{productId}_delete for http method type DELETE 
# RoostTestHash=47d9fe845f
# 
# 

# ********RoostGPT********
Feature: Product management

  Background:
    * def urlBase = karate.properties['nnnn_URL_BASE'] || karate.get('urlBase', 'http://localhost:4010')
    * configure headers = { Authorization: #(karate.properties['nnnn_AUTH_TOKEN']) }

  Scenario Outline: Attempt to delete a product with varying productId
    Given url urlBase
    And path 'products', <productId>
    When method delete
    Then status <expectedStatus>
    And match response == <expectedResponse>

    Examples:
      | productId | expectedStatus | expectedResponse |
      |      1001 |            200 | '#null'          |
      |      9999 |            404 |                  |
