# ********RoostGPT********

# Test generated by RoostGPT for test sampleKarateEnv using AI Type Open AI and AI Model gpt-4-turbo
# 
# Feature file generated for /products/{productId}_get for http method type GET 
# RoostTestHash=52a171b52e
# 
# 

# ********RoostGPT********
Feature: Test /products/{productId} endpoint

  Background:
    * def urlBase = karate.properties['nnnn_URL_BASE'] || karate.get('urlBase', 'http://localhost:4010')
    * url urlBase
    * configure headers = { Authorization: #(karate.properties['nnnn_AUTH_TOKEN']) }

  Scenario Outline: Get product by ID - Successful Case
    Given path 'products', <productId>
    When method get
    Then status 200
    And match response == { id: #number, name: '#string', description: '#string', price: #number }
    And match response.id == <productId>
    And match response.name == '#string'
    And match response.description == '#string'
    And match response.price == #number

    Examples:
      | read('products_productId_get.csv') |

  Scenario: Get product by ID - Product Not Found
    Given path 'products', 99999
    When method get
    Then status 404
    And match response == { message: '#string' }
