# ********RoostGPT********

# Test generated by RoostGPT for test sampleKarateEnv using AI Type Open AI and AI Model gpt-4-turbo
# 
# Feature file generated for /products_post for http method type POST 
# RoostTestHash=2c080099fd
# 
# 

# ********RoostGPT********
Feature: Product Management API

  Background:
    * def urlBase = karate.properties['nnnn_URL_BASE'] || karate.get('urlBase', 'http://localhost:4010')
    * url urlBase
    * configure headers = { Authorization: #(karate.properties['nnnn_AUTH_TOKEN']) }

  Scenario Outline: Add a new product to the store with valid inputs
    Given path '/products'
    And request
      """
      <body>
      """
    When method POST
    Then status 200
    And match response contains { id: '#number', name: '#string', description: '#string', price: '#number' }

    Examples:
      | read('products_post.csv') |

  Scenario: Add a new product with invalid input
    Given path '/products'
    And request
      """
      { "id": "NaN", "name": "", "description": "Invalid product", "price": "NaN" }
      """
    When method POST
    Then status 405

  Scenario: Add a new product without authorization
    * configure headers = {}
    Given path '/products'
    And request
      """
      { "id": 103, "name": "grape", "description": "Sweet grapes", "price": 25 }
      """
    When method POST
    Then status 401
