# ********RoostGPT********

# Test generated by RoostGPT for test sampleKarateEnv using AI Type Open AI and AI Model gpt-4-turbo
# 
# Feature file generated for /products_post for http method type POST 
# RoostTestHash=2c080099fd
# 
# 

# ********RoostGPT********
Feature: Product Management API

  Background:
    * def urlBase = karate.properties['nnnn_URL_BASE'] || karate.get('urlBase', 'http://localhost:4010')
    * url urlBase
    * configure headers = { Authorization: #(karate.properties['nnnn_AUTH_TOKEN']) }

  Scenario Outline: Create a new product with valid data
    Given path '/products'
    And request
      """
      <body>
      """
    When method post
    Then status 200
    And match response ==
      """
      <expectedResponse>
      """

    Examples:
      | read('products_post.csv') |

  Scenario Outline: Attempt to create a product with invalid data
    Given path '/products'
    And request
      """
      <body>
      """
    When method post
    Then status 405

    Examples:
      | body                                                                     |
      | { "id": "abc", "name": "", "description": "Invalid data", "price": -10 } |
      | { "id": null, "name": "Toy", "description": "Missing ID", "price": 30 }  |

  Scenario: Verify response headers and content type for a successful operation
    Given path '/products'
    And request
      """
      { "id": 103, "name": "Tablet", "description": "Brand new tablet", "price": 300 }
      """
    When method post
    Then status 200
    And match header Content-Type == 'application/json'
    And match response contains
      """
      { "id": "#number", "name": "#string", "description": "#string", "price": "#number" }
      """
