# ********RoostGPT********

# Test generated by RoostGPT for test sampleKarateEnv using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Feature file generated for /products/{productId}_get for http method type GET 
# RoostTestHash=52a171b52e
# 
# 

# ********RoostGPT********
Feature: API Tests for /products/{productId}

  Background:
    * def urlBase = karate.properties['URL_BASE'] || karate.get('urlBase', 'http://localhost:4010')
    * url urlBase
    * configure headers = { Authorization: #(karate.properties['AUTH_TOKEN']) }

  Scenario Outline: Validate GET /products/{productId} with valid productId
    Given path '/products/<productId>'
    When method GET
    Then status 200
    And match response == """ #object """
    And match response.id == '#number'
    And match response.name == '#string'
    And match response.description == '#string'
    And match response.price == '#number'

    Examples:
      | read('products_productId_get.csv') |

  Scenario Outline: Handle GET /products/{productId} with non-existent productId
    Given path '/products/<productId>'
    When method GET
    Then status 404

    Examples:
      | productId |
      |       999 |
      |     12345 |
      |         0 |

  Scenario: Validate input with invalid productId - negative number
    Given path '/products/-1'
    When method GET
    Then status 400

  Scenario: Validate input with invalid productId - non-numeric
    Given path '/products/abc'
    When method GET
    Then status 400

  Scenario: Validate input with invalid productId - null value
    Given path '/products/null'
    When method GET
    Then status 400
