# ********RoostGPT********

# Test generated by RoostGPT for test sampleKarateEnv using AI Type  and AI Model 
# 
# Feature file generated for /products/{productId}_get for http method type GET 
# RoostTestHash=52a171b52e
# 
# 

# ********RoostGPT********
Feature: Product Management

  Background:
    * def urlBase = karate.properties['nnnn_URL_BASE'] || karate.get('urlBase', 'http://localhost:4010')
    * url urlBase
    * configure headers = { Authorization: #(karate.properties['nnnn_AUTH_TOKEN']) }

  Scenario: Get Product by ID - Successful Case
    Given path 'products', '<productId>'
    When method get
    Then status 200
    And match response ==
      """
      { 
        id: '#number', 
        name: '#string', 
        description: '#string', 
        price: '#number' 
      }
      """
    And match response.id == '<productId>'

  Scenario Outline: Get Product by ID - Product Not Found
    Given path 'products', '<productId>'
    When method get
    Then status 404
    And match response ==
      """
      { 
        message: '#string' 
      }
      """

    Examples:
      | productId |
      | 999999999 |
