# ********RoostGPT********

# Test generated by RoostGPT for test sampleKarateEnv using AI Type  and AI Model 
# 
# Feature file generated for /products/{productId}_put for http method type PUT 
# RoostTestHash=6762b8ac71
# 
# 

# ********RoostGPT********
Feature: Product Management

  Background:
    * def urlBase = karate.properties['nnnn_URL_BASE'] || karate.get('urlBase', 'http://localhost:4010')
    * url urlBase
    * configure headers = { Authorization: #(karate.properties['nnnn_AUTH_TOKEN']) }

  @updateProduct
  Scenario Outline: Update existing product
    Given path 'products', <productId>
    And request
      """
      { 
        "id": <id>, 
        "name": <name>, 
        "description": <description>, 
        "price": <price> 
      }
      """
    When method put
    Then status 200
    And match response == { "id": "#(id)", "name": "#(name)", "description": "#(description)", "price": "#(price)" }
    And match response contains { "id": "#number", "name": "#string", "description": "#string", "price": "#number" }

    Examples:
      | read('products_productId_put.csv') |

  @updateProductNotFound
  Scenario: Update product that does not exist
    Given path 'products', 999
    And request
      """
      { 
        "id": 999, 
        "name": "ghost", 
        "description": "nonexistent product", 
        "price": 999 
      }
      """
    When method put
    Then status 404
    And match response.path == 'products/999'
