# ********RoostGPT********

# Test generated by RoostGPT for test sampleKarateEnv using AI Type Open AI and AI Model gpt-4-turbo
# 
# Feature file generated for /products/{productId}_delete for http method type DELETE 
# RoostTestHash=47d9fe845f
# 
# 

# ********RoostGPT********
Feature: Product management

  Background:
    * def urlBase = karate.properties['nnnn_URL_BASE'] || karate.get('urlBase', 'http://localhost:4010')
    * url urlBase
    * configure headers = { Authorization: #(karate.properties['nnnn_AUTH_TOKEN']) }

  Scenario Outline: Delete a product with valid productId
    Given path 'products', <productId>
    When method delete
    Then status 200
    And match response == '#null'

    Examples:
      | read('products_productId_delete.csv') |

  Scenario: Attempt to delete a product with an invalid productId
    Given path 'products', 9999
    When method delete
    Then status 404

  Scenario: Delete a product without authorization header
    * configure headers = {}
    Given path 'products', 101
    When method delete
    Then status 401
